import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';

import '../utils/i18n_audit.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  // Translations for English
  Map<String, String> _englishTranslations = {
    'appName': 'E-commerce Client',
    'home': 'Home',
    'categories': 'Categories',
    'cart': 'Cart',
    'orders': 'Orders',
    'profile': 'Profile',
    'specialOrder': 'Special Order',
    'messaging': 'Messaging',
    'settings': 'Settings',
    'language': 'Language',
    'helpSupport': 'Help & Support',
    'login': 'Login',
    'register': 'Register',
    'email': 'Email',
    'password': 'Password',
    'forgotPassword': 'Forgot Password?',
    'search': 'Search',
    'popularProducts': 'Popular Products',
    'addToCart': 'Add to Cart',
    'checkout': 'Checkout',
    'total': 'Total',
    'confirmOrder': 'Confirm Order',
    'orderHistory': 'Order History',
    'trackOrder': 'Track Order',
    'uploadImage': 'Upload Image',
    'productName': 'Product Name',
    'quantity': 'Quantity',
    'description': 'Description',
    'send': 'Send',
    'message': 'Message',
    'cart_empty': 'Your cart is empty',
    'notification_default_title': 'Notification',
    'open': 'Open',
    'push_title_order_status': 'Order update',
    'push_title_cart_abandoned': 'Cart reminder',
    'push_title_promotion': 'Promotion',
    'push_body_order_status': 'Order{orderLabel}: {status}',
    'push_order_status_default_status': 'updated',
    'push_body_cart_abandoned_with_count': 'You have {count} item(s) in your cart.',
    'push_body_cart_abandoned': 'You have items in your cart.',
    'push_body_promotion': 'Discover our offers.',
    'order_status_pending': 'Pending',
    'order_status_confirmed': 'Confirmed',
    'order_status_shipped': 'Shipped',
    'order_status_delivered': 'Delivered',
    'order_status_cancelled': 'Cancelled',
    'order_status_refunded': 'Refunded',
    'menu': 'Menu',
    'favorites': 'Favorites',
    'promotions': 'Promotions',
    'chat': 'Chat',
    'logout': 'Logout',
    'refresh': 'Refresh',
    'retry': 'Retry',
    'clear_filter': 'Clear filter',
    'discover': 'Discover',
    'discover_products': 'Discover our products',
    'continue_shopping': 'Continue shopping',
    'items_count': '{count} item(s)',
    'delivery': 'Delivery',
    'out_of_stock': 'Out of stock',
    'recommended_for_you': 'Recommended for you',
    'our_products': 'Our Products',
    'search_products_hint': '🔍 What are you looking for?',
    'no_products_available': 'No products available',
    'no_products_in_category': 'No products in this category',
    'limited_offers_discounts': 'Limited-time offers and discounts',
    'featured': 'Featured',
    'pull_to_refresh': 'Pull down to refresh',
    'no_featured': 'No featured items for now',
    'no_promotions': 'No promotions at the moment',
    'no_favorites': 'No favorites',
    'favorites_empty_hint': 'Add your favorite products here',
    'explore_products': 'Explore products',
    'collections': 'Collections',
    'shared': 'Shared',
    'sort_recent': 'Recent',
    'sort_name': 'Name',
    'sort_price_asc': 'Price ↑',
    'sort_price_desc': 'Price ↓',
    'messages': 'Messages',
    'support_assistance': 'Support & Assistance',
    'search_conversation_hint': 'Search a conversation...',
    'no_conversation': 'No conversation',
    'start_new_conversation': 'Start a new conversation',
    'conversation_number': 'Conversation #{id}',
    'no_message': 'No message',
    'yesterday': 'Yesterday',
    'now': 'Now',
    'day_short': 'd',
    'hour_short': 'h',
    'minute_short': 'm',
    'filter': 'Filter',
    'filter_categories': 'Filter categories',
    'all': 'All',
    'popular': 'Popular',
    'new': 'New',
    'cancel': 'Cancel',
    'apply': 'Apply',
    'no_results': 'No results',
    'try_another_keyword': 'Try another keyword.',
    'search_category_hint': 'Search a category...',
    'products_count': '{count} product(s)',
    'no_categories': 'No categories',
    'no_categories_hint': "You don't have any categories at the moment.",
    'error_loading': 'Loading error',
    'cart_loading': 'Loading cart…',
    'loading_categories': 'Loading categories…',
    'category': 'Category',
    'support_admin': 'Admin Support',
    'my_account': 'My account',
    'navigation': 'Navigation',
    'special_orders': 'Special orders',
    'new_special_order': 'New special order',
    'my_special_orders': 'My special orders',
    'personalization_gift': 'Personalization / Gift',
    'coming_soon': '{label}: coming soon',
    'favorites_not_found_title': 'Favorite products not found',
    'favorites_not_found_hint': 'Reload the product list.',
    'product': 'Product',
    'removed_from_cart': '{name} removed from cart',
    'removed_from_favorites': '{name} removed from favorites',
    'unnamed_product': 'Unnamed product',
    'no_brand': 'No brand',
    'my_collections': 'My Collections',
    'create_collection': 'Create a collection',
    'collection_summer_2024': 'Summer 2024',
    'collection_essentials': 'Essentials',
    'collection_gifts': 'Gifts',
    'store_name': 'GBA Store',
    'loading_products': 'Loading products…',
    'welcome_to_store': 'Welcome to {store}',
    'see_all': 'See all',
    'error_loading_with_details': 'Loading error: {error}',
    'added_to_cart': '{name} added to cart',
    'page_not_found_title': 'Page not found',
    'no_route_for': 'No route for: {route}',
    'back_to_home': 'Back to home',
    'ad_mega_sale_title': '🎯 MEGA SALE -50%',
    'ad_mega_sale_subtitle': 'On all smartphones',
    'ad_free_delivery_title': '🚚 Free Delivery',
    'ad_free_delivery_subtitle': 'For any order over 100€',
    'ad_flash_deal_title': '⚡ Flash Deal',
    'ad_flash_deal_subtitle': 'New offers every day',
    'ad_promo_code_title': '🎁 Promo code: SAVE20',
    'ad_promo_code_subtitle': '20% instant discount',
  };

  // Translations for French
  Map<String, String> _frenchTranslations = {
    'appName': 'GBA',
    'home': 'Accueil',
    'categories': 'Catégories',
    'cart': 'Panier',
    'orders': 'Commandes',
    'profile': 'Profil',
    'specialOrder': 'Commande Spéciale',
    'messaging': 'Messagerie',
    'settings': 'Paramètres',
    'language': 'Langue',
    'helpSupport': 'Aide et Support',
    'login': 'Connexion',
    'register': 'Inscription',
    'email': 'Email',
    'password': 'Mot de passe',
    'forgotPassword': 'Mot de passe oublié?',
    'search': 'Recherche',
    'popularProducts': 'Produits Populaires',
    'addToCart': 'Ajouter au Panier',
    'checkout': 'Validation',
    'total': 'Total',
    'confirmOrder': 'Confirmer la Commande',
    'orderHistory': 'Historique des Commandes',
    'trackOrder': 'Suivre la Commande',
    'uploadImage': 'Télécharger une Image',
    'productName': 'Nom du Produit',
    'quantity': 'Quantité',
    'description': 'Description',
    'send': 'Envoyer',
    'message': 'Message',
    'cart_empty': 'Votre panier est vide',
    'notification_default_title': 'Notification',
    'open': 'Ouvrir',
    'push_title_order_status': 'Mise à jour commande',
    'push_title_cart_abandoned': 'Panier en attente',
    'push_title_promotion': 'Promotion',
    'push_body_order_status': 'Commande{orderLabel}: {status}',
    'push_order_status_default_status': 'mise à jour',
    'push_body_cart_abandoned_with_count': 'Tu as {count} article(s) dans ton panier.',
    'push_body_cart_abandoned': 'Tu as des articles dans ton panier.',
    'push_body_promotion': 'Découvre nos offres.',
    'order_status_pending': 'En attente',
    'order_status_confirmed': 'Confirmée',
    'order_status_shipped': 'Expédiée',
    'order_status_delivered': 'Livrée',
    'order_status_cancelled': 'Annulée',
    'order_status_refunded': 'Remboursée',
    'menu': 'Menu',
    'favorites': 'Favoris',
    'promotions': 'Promotions',
    'chat': 'Chat',
    'logout': 'Déconnexion',
    'refresh': 'Rafraîchir',
    'retry': 'Réessayer',
    'clear_filter': 'Effacer filtre',
    'discover': 'Découvrir',
    'discover_products': 'Découvrez nos produits',
    'continue_shopping': 'Continuer vos achats',
    'items_count': '{count} article(s)',
    'delivery': 'Livraison',
    'out_of_stock': 'Rupture de stock',
    'recommended_for_you': 'Recommandé pour vous',
    'our_products': 'Nos Produits',
    'search_products_hint': '🔍 Que recherchez-vous?',
    'no_products_available': 'Aucun produit disponible',
    'no_products_in_category': 'Aucun produit dans cette catégorie',
    'limited_offers_discounts': 'Offres limitées et réductions',
    'featured': 'Vedettes',
    'pull_to_refresh': 'Tire vers le bas pour rafraîchir',
    'no_featured': 'Aucune vedette pour le moment',
    'no_promotions': 'Aucune promotion en cours',
    'no_favorites': 'Aucun favori',
    'favorites_empty_hint': 'Ajoutez vos produits préférés ici',
    'explore_products': 'Explorer les produits',
    'collections': 'Collections',
    'shared': 'Partagés',
    'sort_recent': 'Récents',
    'sort_name': 'Nom',
    'sort_price_asc': 'Prix ↑',
    'sort_price_desc': 'Prix ↓',
    'messages': 'Messages',
    'support_assistance': 'Support & Assistance',
    'search_conversation_hint': 'Rechercher une conversation...',
    'no_conversation': 'Aucune conversation',
    'start_new_conversation': 'Commencez une nouvelle conversation',
    'conversation_number': 'Conversation #{id}',
    'no_message': 'Pas de message',
    'yesterday': 'Hier',
    'now': 'Maintenant',
    'day_short': 'j',
    'hour_short': 'h',
    'minute_short': 'm',
    'filter': 'Filtrer',
    'filter_categories': 'Filtrer les catégories',
    'all': 'Tout',
    'popular': 'Populaires',
    'new': 'Nouveautés',
    'cancel': 'Annuler',
    'apply': 'Appliquer',
    'no_results': 'Aucun résultat',
    'try_another_keyword': 'Essaie un autre mot-clé.',
    'search_category_hint': 'Rechercher une catégorie…',
    'products_count': '{count} produits',
    'no_categories': 'Aucune catégorie',
    'no_categories_hint': 'Vous n\'avez aucune catégorie pour le moment.',
    'error_loading': 'Erreur de chargement',
    'cart_loading': 'Chargement du panier…',
    'loading_categories': 'Chargement des catégories…',
    'category': 'Catégorie',
    'support_admin': 'Support Admin',
    'my_account': 'Mon compte',
    'navigation': 'Navigation',
    'special_orders': 'Commandes spéciales',
    'new_special_order': 'Nouvelle commande spéciale',
    'my_special_orders': 'Mes commandes spéciales',
    'personalization_gift': 'Personnalisation / Cadeau',
    'coming_soon': '{label} : bientôt disponible',
    'favorites_not_found_title': 'Produits favoris introuvables',
    'favorites_not_found_hint': 'Recharge la liste des produits.',
    'product': 'Produit',
    'removed_from_cart': '{name} retiré du panier',
    'removed_from_favorites': '{name} retiré des favoris',
    'unnamed_product': 'Produit sans nom',
    'no_brand': 'Sans marque',
    'my_collections': 'Mes Collections',
    'create_collection': 'Créer une collection',
    'collection_summer_2024': 'Été 2024',
    'collection_essentials': 'Essentiels',
    'collection_gifts': 'Cadeaux',
    'store_name': 'GBA Store',
    'loading_products': 'Chargement des produits…',
    'welcome_to_store': 'Bienvenue chez {store}',
    'see_all': 'Voir tout',
    'error_loading_with_details': 'Erreur de chargement: {error}',
    'added_to_cart': '{name} ajouté au panier',
    'page_not_found_title': 'Page introuvable',
    'no_route_for': 'Aucune route pour : {route}',
    'back_to_home': 'Retour à l\'accueil',
    'ad_mega_sale_title': '🎯 MEGA SOLDES -50%',
    'ad_mega_sale_subtitle': 'Sur tous les smartphones',
    'ad_free_delivery_title': '🚚 Livraison Gratuite',
    'ad_free_delivery_subtitle': 'Pour toute commande +100€',
    'ad_flash_deal_title': '⚡ Flash Deal',
    'ad_flash_deal_subtitle': 'Nouvelles offres chaque jour',
    'ad_promo_code_title': '🎁 Code Promo: SAVE20',
    'ad_promo_code_subtitle': '20% de réduction immédiate',
  };

  // Translations for Arabic
  Map<String, String> _arabicTranslations = {
    'appName': 'عميل التجارة الإلكترونية',
    'home': 'الرئيسية',
    'categories': 'الفئات',
    'cart': 'السلة',
    'orders': 'الطلبات',
    'profile': 'الملف الشخصي',
    'specialOrder': 'طلب خاص',
    'messaging': 'المراسلة',
    'settings': 'الإعدادات',
    'language': 'اللغة',
    'helpSupport': 'المساعدة والدعم',
    'login': 'تسجيل الدخول',
    'register': 'تسجيل',
    'email': 'البريد الإلكتروني',
    'password': 'كلمة المرور',
    'forgotPassword': 'هل نسيت كلمة المرور؟',
    'cart_empty': 'سلة التسوق فارغة',
    'search': 'بحث',
    'popularProducts': 'المنتجات الشائعة',
    'addToCart': 'أضف إلى السلة',
    'checkout': 'التحقق من',
    'total': 'المجموع',
    'confirmOrder': 'تأكيد الطلب',
    'orderHistory': 'سجل الطلبات',
    'trackOrder': 'تتبع الطلب',
    'uploadImage': 'تحميل صورة',
    'productName': 'اسم المنتج',
    'quantity': 'الكمية',
    'description': 'الوصف',
    'send': 'إرسال',
    'message': 'رسالة',
    'notification_default_title': 'إشعار',
    'open': 'فتح',
    'push_title_order_status': 'تحديث الطلب',
    'push_title_cart_abandoned': 'تذكير بالسلة',
    'push_title_promotion': 'عرض ترويجي',
    'push_body_order_status': 'الطلب{orderLabel}: {status}',
    'push_order_status_default_status': 'تم تحديثه',
    'push_body_cart_abandoned_with_count': 'لديك {count} عنصرًا في سلتك.',
    'push_body_cart_abandoned': 'لديك عناصر في سلتك.',
    'push_body_promotion': 'اكتشف عروضنا.',
    'order_status_pending': 'قيد الانتظار',
    'order_status_confirmed': 'تم التأكيد',
    'order_status_shipped': 'تم الشحن',
    'order_status_delivered': 'تم التسليم',
    'order_status_cancelled': 'تم الإلغاء',
    'order_status_refunded': 'تم الاسترداد',
    'menu': 'القائمة',
    'favorites': 'المفضلة',
    'promotions': 'العروض',
    'chat': 'الدردشة',
    'logout': 'تسجيل الخروج',
    'refresh': 'تحديث',
    'retry': 'إعادة المحاولة',
    'clear_filter': 'مسح التصفية',
    'discover': 'اكتشف',
    'discover_products': 'اكتشف منتجاتنا',
    'continue_shopping': 'متابعة التسوق',
    'items_count': '{count} عنصر',
    'delivery': 'التوصيل',
    'out_of_stock': 'غير متوفر',
    'recommended_for_you': 'موصى به لك',
    'our_products': 'منتجاتنا',
    'search_products_hint': '🔍 ماذا تبحث عنه؟',
    'no_products_available': 'لا توجد منتجات متاحة',
    'no_products_in_category': 'لا توجد منتجات في هذه الفئة',
    'limited_offers_discounts': 'عروض وخصومات لفترة محدودة',
    'featured': 'مختارة',
    'pull_to_refresh': 'اسحب للأسفل للتحديث',
    'no_featured': 'لا توجد عناصر مختارة حالياً',
    'no_promotions': 'لا توجد عروض حالياً',
    'no_favorites': 'لا توجد مفضلات',
    'favorites_empty_hint': 'أضف منتجاتك المفضلة هنا',
    'explore_products': 'استكشاف المنتجات',
    'collections': 'المجموعات',
    'shared': 'المشتركة',
    'sort_recent': 'الأحدث',
    'sort_name': 'الاسم',
    'sort_price_asc': 'السعر ↑',
    'sort_price_desc': 'السعر ↓',
    'messages': 'الرسائل',
    'support_assistance': 'الدعم والمساعدة',
    'search_conversation_hint': 'ابحث عن محادثة...',
    'no_conversation': 'لا توجد محادثة',
    'start_new_conversation': 'ابدأ محادثة جديدة',
    'conversation_number': 'محادثة #{id}',
    'no_message': 'لا توجد رسالة',
    'yesterday': 'أمس',
    'now': 'الآن',
    'day_short': 'ي',
    'hour_short': 'س',
    'minute_short': 'د',
    'filter': 'تصفية',
    'filter_categories': 'تصفية الفئات',
    'all': 'الكل',
    'popular': 'الأكثر شيوعاً',
    'new': 'الجديد',
    'cancel': 'إلغاء',
    'apply': 'تطبيق',
    'no_results': 'لا توجد نتائج',
    'try_another_keyword': 'جرّب كلمة أخرى.',
    'search_category_hint': 'ابحث عن فئة…',
    'products_count': '{count} منتج',
    'no_categories': 'لا توجد فئات',
    'no_categories_hint': 'ليس لديك أي فئات في الوقت الحالي.',
    'error_loading': 'خطأ في التحميل',
    'cart_loading': 'جارٍ تحميل السلة…',
    'loading_categories': 'جارٍ تحميل الفئات…',
    'category': 'فئة',
    'support_admin': 'دعم المشرف',
    'my_account': 'حسابي',
    'navigation': 'التنقل',
    'special_orders': 'طلبات خاصة',
    'new_special_order': 'طلب خاص جديد',
    'my_special_orders': 'طلباتي الخاصة',
    'personalization_gift': 'تخصيص / هدية',
    'coming_soon': '{label}: قريباً',
    'favorites_not_found_title': 'تعذر العثور على المنتجات المفضلة',
    'favorites_not_found_hint': 'أعد تحميل قائمة المنتجات.',
    'product': 'منتج',
    'removed_from_cart': 'تمت إزالة {name} من السلة',
    'removed_from_favorites': 'تمت إزالة {name} من المفضلة',
    'unnamed_product': 'منتج بدون اسم',
    'no_brand': 'بدون علامة تجارية',
    'my_collections': 'مجموعاتي',
    'create_collection': 'إنشاء مجموعة',
    'collection_summer_2024': 'صيف 2024',
    'collection_essentials': 'الأساسيات',
    'collection_gifts': 'هدايا',
    'store_name': 'متجر GBA',
    'loading_products': 'جارٍ تحميل المنتجات…',
    'welcome_to_store': 'مرحبًا بك في {store}',
    'see_all': 'عرض الكل',
    'error_loading_with_details': 'خطأ في التحميل: {error}',
    'added_to_cart': 'تمت إضافة {name} إلى السلة',
    'page_not_found_title': 'الصفحة غير موجودة',
    'no_route_for': 'لا يوجد مسار لـ: {route}',
    'back_to_home': 'العودة إلى الرئيسية',
    'ad_mega_sale_title': '🎯 تخفيضات كبرى -50%',
    'ad_mega_sale_subtitle': 'على جميع الهواتف الذكية',
    'ad_free_delivery_title': '🚚 توصيل مجاني',
    'ad_free_delivery_subtitle': 'للطلبات فوق 100€',
    'ad_flash_deal_title': '⚡ صفقة سريعة',
    'ad_flash_deal_subtitle': 'عروض جديدة كل يوم',
    'ad_promo_code_title': '🎁 كود خصم: SAVE20',
    'ad_promo_code_subtitle': 'خصم فوري 20%',
  };

  String translate(String key) {
    switch (locale.languageCode) {
      case 'en':
        if (!_englishTranslations.containsKey(key)) {
          I18nAudit.instance.reportMissingKey(key: key, locale: locale);
        }
        return _englishTranslations[key] ?? key;
      case 'fr':
        if (!_frenchTranslations.containsKey(key)) {
          I18nAudit.instance.reportMissingKey(key: key, locale: locale);
        }
        return _frenchTranslations[key] ?? key;
      case 'ar':
        if (!_arabicTranslations.containsKey(key)) {
          I18nAudit.instance.reportMissingKey(key: key, locale: locale);
        }
        return _arabicTranslations[key] ?? key;
      default:
        if (!_englishTranslations.containsKey(key)) {
          I18nAudit.instance.reportMissingKey(key: key, locale: locale);
        }
        return _englishTranslations[key] ?? key;
    }
  }

  String translateParams(String key, Map<String, String> params) {
    var value = translate(key);
    for (final entry in params.entries) {
      value = value.replaceAll('{${entry.key}}', entry.value);
    }
    return value;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'fr', 'ar'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
