import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';

import '../utils/i18n_audit.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  // Translations for English
  late final Map<String, String> _englishTranslations = {
    'appName': 'E-commerce Client',
    'home': 'Home',
    'categories': 'Categories',
    'cart': 'Cart',
    'orders': 'Orders',
    'profile': 'Profile',
    'view': 'View',
    'delete': 'Delete',
    'points': 'Points',
    'first_name': 'First name',
    'last_name': 'Last name',
    'bio': 'Bio',
    'postal_code': 'Postal code',
    'not_provided': 'Not provided',
    'profile_completion_title': 'Profile completion',
    'profile_completion_hint': 'Complete your profile to speed up checkout.',
    'complete_now': 'Complete now',
    'profile_tab_info': 'Info',
    'profile_tab_edit': 'Edit',
    'personal_information': 'Personal information',
    'profile_photo': 'Profile photo',
    'cover_photo': 'Cover photo',
    'choose_cover': 'Choose a cover',
    'choose_photo': 'Choose a photo',
    'camera': 'Camera',
    'gallery': 'Gallery',
    'photo_updated_success': 'Photo updated successfully!',
    'photo_update_error': 'Error updating photo',
    'profile_updated_success': 'Profile updated successfully!',
    'fill_required_fields': 'Please fill in all required fields',
    'invalid_phone_number': 'Invalid phone number',
    'quick_actions': 'Quick actions',
    'specialOrder': 'Special Order',
    'messaging': 'Messaging',
    'settings': 'Settings',
    'language': 'Language',
    'helpSupport': 'Help & Support',
    'login': 'Login',
    'register': 'Register',
    'create_account': 'Create an account',
    'driver_app_title': 'GBA Driver',
    'driver_login_subtitle': 'Sign in to access your deliveries',
    'driver_email_label': 'Work email',
    'driver_email_required': 'Enter your email',
    'driver_email_invalid': 'Invalid email',
    'driver_password_label': 'Password',
    'driver_password_required': 'Enter your password',
    'driver_password_min': 'Minimum 6 characters',
    'driver_login_button': 'Sign in',
    'register_subtitle_join_store': 'Join GBA Store in 30 seconds',
    'full_name': 'Full name',
    'enter_your_name': 'Please enter your name',
    'enter_your_email': 'Please enter your email',
    'invalid_email': 'Invalid email',
    'enter_your_password': 'Please enter your password',
    'confirm_your_password': 'Please confirm your password',
    'password_min_length_register': 'Password must be at least 6 characters.',
    'accept_legal_prefix': 'I accept the ',
    'accept_legal_and': ' and the ',
    'already_have_account': 'Already have an account?',
    'register_accept_legal_required': 'Please accept the Terms of Service and Privacy Policy.',
    'register_account_created_check_email': 'Account created. Check your email then log in.',
    'admin_support_available': 'Customer service available',
    'user_not_logged_in': 'User not logged in',
    'email': 'Email',
    'password': 'Password',
    'forgotPassword': 'Forgot Password?',
    'forgot_password_title': 'Forgot password',
    'forgot_password_instruction':
        "Enter your email. We'll send you a link to set a new password.",
    'forgot_password_send_link': 'Send link',
    'forgot_password_email_sent': 'Email sent. Check your inbox (and Spam).',
    'reset_password_instruction': 'Set your new password.',
    'validate': 'Validate',
    'search': 'Search',
    'popularProducts': 'Popular Products',
    'addToCart': 'Add to Cart',
    'checkout': 'Checkout',
    'total': 'Total',
    'confirmOrder': 'Confirm Order',
    'orderHistory': 'Order History',
    'trackOrder': 'Track Order',
    'uploadImage': 'Upload Image',
    'productName': 'Product Name',
    'quantity': 'Quantity',
    'description': 'Description',
    'send': 'Send',
    'message': 'Message',
    'cart_empty': 'Your cart is empty',
    'notification_default_title': 'Notification',
    'open': 'Open',
    'push_title_order_status': 'Order update',
    'push_title_cart_abandoned': 'Cart reminder',
    'push_title_promotion': 'Promotion',
    'push_body_order_status': 'Order{orderLabel}: {status}',
    'push_order_status_default_status': 'updated',
    'push_body_cart_abandoned_with_count': 'You have {count} item(s) in your cart.',
    'push_body_cart_abandoned': 'You have items in your cart.',
    'push_body_promotion': 'Discover our offers.',
    'order_status_pending': 'Pending',
    'order_status_confirmed': 'Confirmed',
    'order_status_shipped': 'Shipped',
    'order_status_delivered': 'Delivered',
    'order_status_cancelled': 'Cancelled',
    'order_status_refunded': 'Refunded',
    'menu': 'Menu',
    'favorites': 'Favorites',
    'promotions': 'Promotions',
    'chat': 'Chat',
    'logout': 'Logout',
    'refresh': 'Refresh',
    'retry': 'Retry',
    'clear_filter': 'Clear filter',
    'discover': 'Discover',
    'discover_products': 'Discover our products',
    'continue_shopping': 'Continue shopping',
    'products': 'Products',
    'my_orders_title': 'My orders',
    'orders_total_count': '{count} order(s) total',
    'no_orders': 'No orders',
    'no_orders_hint': 'Your orders will appear here',
    'order_details_title': 'Order details',
    'order_information': 'Information',
    'name': 'Name',
    'phone': 'Phone',
    'country': 'Country',
    'city': 'City',
    'district': 'District',
    'address': 'Address',
    'number': 'Number',
    'date': 'Date',
    'payment': 'Payment',
    'customer': 'Customer',
    'shipping_address_title': 'Shipping address',
    'items': 'Items',
    'no_items': 'No items',
    'subtotal': 'Subtotal',
    'not_available': 'N/A',
    'unknown': 'Unknown',
    'order_status_processing': 'Processing',
    'added_to_favorites': '{name} added to favorites',
    'leave_review': 'Leave a review',
    'edit_my_review': 'Edit my review',
    'edit': 'Edit',
    'review_comment_optional': 'Comment (optional)',
    'review_submitted_bonus': 'Review submitted. +5 points added',
    'review_error_with_details': 'Review error: {error}',
    'product_not_found': 'Product not found',
    'view_cart': 'View cart',
    'in_stock_with_count': 'In stock ({count})',
    'no_description_available': 'No description available',
    'reviews': 'Reviews',
    'no_reviews_yet': 'No reviews yet',
    'similar_products': 'Similar products',
    'items_count': '{count} item(s)',
    'delivery': 'Delivery',
    'out_of_stock': 'Out of stock',
    'recommended_for_you': 'Recommended for you',
    'our_products': 'Our Products',
    'search_products_hint': 'What are you looking for?',
    'no_products_available': 'No products available',
    'no_products_in_category': 'No products in this category',
    'limited_offers_discounts': 'Limited-time offers and discounts',
    'featured': 'Featured',
    'pull_to_refresh': 'Pull down to refresh',
    'no_featured': 'No featured items for now',
    'no_promotions': 'No promotions at the moment',
    'no_favorites': 'No favorites',
    'favorites_empty_hint': 'Add your favorite products here',
    'explore_products': 'Explore products',
    'collections': 'Collections',
    'shared': 'Shared',
    'sort_recent': 'Recent',
    'sort_name': 'Name',
    'sort_price_asc': 'Price ↑',
    'sort_price_desc': 'Price ↓',
    'messages': 'Messages',
    'support_assistance': 'Support & Assistance',
    'search_conversation_hint': 'Search a conversation...',
    'no_conversation': 'No conversation',
    'start_new_conversation': 'Start a new conversation',
    'conversation_number': 'Conversation #{id}',
    'no_message': 'No message',
    'yesterday': 'Yesterday',
    'now': 'Now',
    'day_short': 'd',
    'hour_short': 'h',
    'minute_short': 'm',
    'filter': 'Filter',
    'filter_categories': 'Filter categories',
    'all': 'All',
    'popular': 'Popular',
    'new': 'New',
    'cancel': 'Cancel',
    'authorize': 'Authorize',
    'notification_permission_rationale': 'Allow GBA to send you notifications for your orders, deliveries and promotions. You can disable them at any time in settings.',
    'apply': 'Apply',
    'press_back_again_to_exit': 'Press back again to exit',
    'no_results': 'No results',
    'try_another_keyword': 'Try another keyword.',
    'search_category_hint': 'Search a category...',
    'products_count': '{count} product(s)',
    'explore': 'Explore',
    'no_categories': 'No categories',
    'no_categories_hint': "You don't have any categories at the moment.",
    'error_loading': 'Loading error',
    'cart_loading': 'Loading cart…',
    'loading_categories': 'Loading categories…',
    'category': 'Category',
    'support_admin': 'Admin Support',
    'my_account': 'My account',
    'navigation': 'Navigation',
    'special_orders': 'Special orders',
    'new_special_order': 'New special order',
    'my_special_orders': 'My special orders',
    'special_order_empty_title': 'No special orders for now',
    'special_order_create_button': 'Create a special order',
    'special_order_generic_title': 'Special order',
    'special_order_loading_error_with_details': 'Loading error: {error}',
    'special_order_shipping_air': 'Air',
    'special_order_shipping_standard': 'Standard',
    'special_order_quantity_delivery': 'Quantity: {qty}  •  Delivery: {shipping}',
    'special_order_quote_with_amount': 'Quote: {amount}',
    'special_order_quote_pending': 'Waiting for quote',
    'special_order_eta_with_range': 'Estimated arrival: {range}',
    'special_order_quote_status_with_status': 'Quote status: {status}',
    'special_order_details_title': 'Special order details',
    'special_order_not_found': 'Special order not found',
    'special_order_status_with_status': 'Status: {status}',
    'special_order_accept_quote': 'Accept',
    'special_order_reject_quote': 'Reject',
    'special_order_negotiate_quote': 'Negotiate (counter-offer)',
    'special_order_history': 'History',
    'special_order_timeline': 'Timeline',
    'special_order_offers_messages': 'Offers / messages',
    'special_order_quote_accepted': 'Quote accepted',
    'special_order_quote_rejected': 'Quote rejected',
    'special_order_counter_offer_sent': 'Counter-offer sent',
    'special_order_reject_dialog_title': 'Reject quote',
    'special_order_counter_dialog_title': 'Make a counter-offer',
    'special_order_unit_price_label': 'Proposed unit price',
    'special_order_shipping_fee_label': 'Proposed shipping fee',
    'special_order_optional_message_label': 'Message (optional)',
    'special_order_invalid_unit_price': 'Invalid unit price',
    'special_order_quote': 'Quote',
    'special_order_subtotal': 'Subtotal',
    'special_order_shipping': 'Shipping',
    'special_order_tax': 'Tax',
    'special_order_service_fee': 'Service',
    'special_order_total': 'Total',
    'special_order_valid_until_with_date': 'Valid until: {date}',
    'special_order_step_indicator': 'Step {current}/{total}',
    'special_order_step_details': 'Details',
    'special_order_step_images': 'Photos',
    'special_order_step_delivery': 'Delivery',
    'special_order_step_summary': 'Summary',
    'save_and_continue': 'Save and continue',
    'back': 'Back',
    'special_order_product_details_title': 'Product details',
    'special_order_product_name_required': 'Product name is required',
    'special_order_invalid_quantity': 'Invalid quantity',
    'special_order_description_required': 'Description is required',
    'special_order_images_optional_title': 'Photos (optional)',
    'special_order_add': 'Add',
    'special_order_images_hint': 'Add images to help identify the product.',
    'special_order_delivery_title': 'Delivery',
    'special_order_location_ready_with_accuracy': 'Location ready (±{meters}m)',
    'special_order_use_my_location': 'Use my location',
    'special_order_detecting_location': 'Detecting your location...',
    'special_order_location_not_available': 'Location not detected yet',
    'special_order_shipping_method': 'Shipping method',
    'special_order_shipping_air_fast': 'By air (faster)',
    'special_order_shipping_other_standard': 'Other way (standard)',
    'special_order_notes_optional': 'Notes (optional)',
    'special_order_notes_hint': 'Details, links, etc.',
    'special_order_summary_title': 'Summary',
    'special_order_summary_product': 'Product',
    'special_order_summary_quantity': 'Quantity',
    'special_order_summary_delivery': 'Delivery',
    'special_order_summary_images': 'Images',
    'special_order_summary_notes': 'Notes',
    'special_order_summary_description': 'Description',
    'special_order_gps_required_before_continue':
        'Enable GPS and save your location before continuing.',
    'special_order_gps_required_submit': 'GPS location is required to submit this special order.',
    'no_internet_connection_title': 'No internet connection',
    'no_internet_connection_message': 'Check your network and tap retry.',
    'notification_body_audio_message': 'Voice message',
    'notification_body_image_message': 'Image',
    'notification_body_new_message': 'New message',
    'special_order_gps_location': 'GPS Location',
    'special_order_confirm_hint': 'By confirming, your request will be sent to the team for processing.',
    'special_order_location_optional': 'Location not available',
    'special_order_description': 'Description',
    'special_order_check_required_fields': 'Please check required fields',
    'special_order_sent': 'Special order sent',
    'special_order_send_error': 'Send error',
    'special_order_draft_restored': 'Draft restored',
    'special_order_geolocation_mobile_only': 'Geolocation is available on mobile.',
    'special_order_enable_location_services': 'Enable phone location services to continue.',
    'special_order_location_permission_denied': 'Location permission denied.',
    'special_order_location_saved_with_accuracy': 'Location saved (±{meters}m)',
    'special_order_location_failed_with_details': 'Unable to get location: {error}',
    'special_order_max_images': 'Maximum {count} images',
    'special_order_max_images_ignored': 'Maximum {count} images (the others were ignored)',
    'special_order_image_too_large_with_size': 'Image too large ({size}MB)',
    'special_order_pick_images_error_with_details': 'Error selecting images: {error}',
    'special_order_status_pending': 'Pending',
    'special_order_status_quoted': 'Quoted',
    'special_order_status_countered': 'Countered',
    'special_order_status_accepted': 'Accepted',
    'special_order_status_rejected': 'Rejected',
    'no_events_yet': 'No events yet',
    'personalization_gift': 'Personalization / Gift',
    'coming_soon': '{label}: coming soon',
    'favorites_not_found_title': 'Favorite products not found',
    'favorites_not_found_hint': 'Reload the product list.',
    'product': 'Product',
    'removed_from_cart': '{name} removed from cart',
    'removed_from_favorites': '{name} removed from favorites',
    'unnamed_product': 'Unnamed product',
    'no_brand': 'No brand',
    'my_collections': 'My Collections',
    'create_collection': 'Create a collection',
    'collection_summer_2024': 'Summer 2024',
    'collection_essentials': 'Essentials',
    'collection_gifts': 'Gifts',
    'store_name': 'GBA Store',
    'loading_products': 'Loading products…',
    'welcome_to_store': 'Welcome to {store}',
    'choose_option_to_continue': 'Choose an option to continue',
    'splash_welcome_full': 'Welcome to Global Business Amdaradir',
    'brand_full_name': 'Global Business Amdaradir',
    'auth_login_title': 'Login',
    'auth_login_subtitle': 'Welcome to Global Business Amdaradir',
    'auth_register_title': 'Create an account',
    'auth_register_subtitle': 'Join Global Business Amdaradir',
    'contact_title': 'Contact',
    'contact_phone_title': 'Phone',
    'contact_facebook_title': 'Facebook',
    'contact_facebook_subtitle': 'Open our Facebook page',
    'contact_tiktok_title': 'TikTok',
    'contact_tiktok_subtitle': 'Open our TikTok profile',
    'contact_open_failed': 'Unable to open link.',
    'cgu': 'Terms of Service',
    'confidentiality': 'Privacy Policy',
    'see_all': 'See all',
    'error_loading_with_details': 'Loading error: {error}',
    'added_to_cart': '{name} added to cart',
    'page_not_found_title': 'Page not found',
    'no_route_for': 'No route for: {route}',
    'back_to_home': 'Back to home',
    'ad_mega_sale_title': '🎫 MEGA SALE -50%',
    'ad_mega_sale_subtitle': 'On all smartphones',
    'ad_free_delivery_title': '🚚 Free Delivery',
    'ad_free_delivery_subtitle': 'For any order over 100€',
    'ad_flash_deal_title': '⚡ Flash Deal',
    'ad_flash_deal_subtitle': 'New offers every day',
    'ad_promo_code_title': '🎁 Promo code: SAVE20',
    'ad_promo_code_subtitle': '20% instant discount',
    'notifications': 'Notifications',
    'appearance': 'Appearance',
    'privacy': 'Privacy',
    'danger_zone': 'Danger zone',
    'push_notifications': 'Push notifications',
    'receive_notifications': 'Receive notifications',
    'notification_preferences': 'Notification preferences',
    'choose_categories': 'Choose categories',
    'sounds': 'Sounds',
    'enable_sound_effects': 'Enable sound effects',
    'vibrations': 'Vibrations',
    'haptic_feedback': 'Haptic feedback',
    'dark_mode': 'Dark mode',
    'enable_dark_theme': 'Enable dark theme',
    'app_language': 'App language',
    'language_french': 'French',
    'language_english': 'English',
    'language_arabic': 'Arabic',
    'change_password': 'Change password',
    'change_password_subtitle': 'Update your password',
    'privacy_policy': 'Privacy policy',
    'privacy_policy_subtitle': 'How we protect your data',
    'terms_of_service': 'Terms of service',
    'terms_of_service_subtitle': 'Read the terms',
    'clear_cache': 'Clear cache',
    'cache_cleared_success': 'Cache cleared successfully',
    'logout_confirm_message': 'Do you really want to log out?',
    'enable_disable_all_notifications': 'Enable/Disable all notifications',
    'notification_category_orders_subtitle': 'Order status, delivery, cancellation',
    'notification_category_promotions_subtitle': 'Offers, discounts, new arrivals',
    'notification_category_messages_subtitle': 'New support/chat messages',
    'save': 'Save',
    'change_password_security_hint': 'For your security, confirm your current password.',
    'current_password': 'Current password',
    'new_password': 'New password',
    'confirm_password': 'Confirm password',
    'error_user_email_not_found': 'Unable to continue: user email not found.',
    'password_min_length': 'The new password must be at least 6 characters.',
    'passwords_do_not_match': 'Passwords do not match.',
    'password_changed_success': 'Password changed.',
    'error_with_details': 'Error: {error}',
    'share_unavailable_with_details': 'Unable to share: {error}',
    'link_copied': 'Link copied',
    'image_saved_to_gallery': 'Image saved to gallery',
    'open_link_unavailable': 'Unable to open the link',
    'image': 'Image',
    'download': 'Download',
    'share': 'Share',
    'view_fullscreen': 'View full screen',
    'copy_link': 'Copy link',
    'chat_error_sending_with_details': 'Send error: {error}',
    'chat_error_sending_image_with_details': 'Image send error: {error}',
    'image_upload_failed': 'Image upload failed',
    'support_client': 'Customer Support',
    'order_number': 'Order #{id}',
    'order_number_label': 'Order number',
    'track_order': 'Track order',
    'order_tracking_title': 'Order status',
    'search_product_hint': 'What are you looking for?',
    'search_history': 'Recent searches',
    'search_clear_history': 'Clear',
    'price': 'Price',
    'reset': 'Reset',
    'filter_min_rating': 'Minimum rating',
    'order_cancelled': 'Order cancelled',
    'current': 'Current',
    'permission_denied': 'Permission denied',
    'start_conversation': 'Start the conversation',
    'we_are_here_to_help': 'We are here to help you',
    'type_your_message': 'Type your message...',
    'conversation_info_title': 'Conversation information',
    'label_id': 'ID',
    'label_status': 'Status',
    'label_priority': 'Priority',
    'label_order': 'Order',
    'label_created_at': 'Created at',
    'today': 'Today',
    'conversation_status_active': 'Active',
    'conversation_status_resolved': 'Resolved',
    'conversation_status_archived': 'Archived',
    'conversation_status_pending': 'Pending',
    'conversation_priority_urgent': 'Urgent',
    'conversation_priority_high': 'High',
    'conversation_priority_normal': 'Normal',
    'conversation_priority_low': 'Low',
    'privacy_policy_section1_title': '1. Collected data',
    'privacy_policy_section1_body':
        'GBA collects the information needed to create your account and process your orders: name, email, phone number, delivery address and order history. This data is stored securely via Supabase (encrypted servers). We do not store your bank card details on our servers.',
    'privacy_policy_section2_title': '2. Use of data',
    'privacy_policy_section2_body':
        'Your data is used for: account authentication and security, order processing and tracking, customer support and in-app chat, service improvements through anonymous statistics, and fraud prevention.',
    'privacy_policy_section2_body_location':
        'If you use geolocation features, your location is used only to facilitate delivery. It is requested only after your explicit consent and is never collected in the background.',
    'privacy_policy_section3_title': '3. Push notifications',
    'privacy_policy_section3_body':
        'If you enable notifications, a Firebase token is used to send you alerts related to orders, deliveries and promotions. You can disable notifications at any time in the app settings.',
    'privacy_policy_section4_title': '4. Sharing and retention',
    'privacy_policy_section4_body':
        'We never sell your data. It may be shared with delivery partners only to complete your delivery. Data is kept for the duration of your account and can be deleted on request. Third-party services used: Supabase (database), Firebase (notifications), Stripe / mobile money providers (payments).',
    'privacy_policy_section5_title': '5. Your rights',
    'privacy_policy_section5_body':
        'You can request access, correction or deletion of your personal data. To exercise these rights or for any privacy question, contact support through the app.',
    'terms_of_service_section1_title': '1. Purpose',
    'terms_of_service_section1_body':
        'These Terms of Service govern the use of the GBA mobile application (Global Business Amdaradir). By creating an account or placing an order, you fully accept these terms. We may update them at any time; changes apply once published in the app.',
    'terms_of_service_section2_title': '2. User account',
    'terms_of_service_section2_body':
        'You must provide accurate information during registration. You are responsible for keeping your credentials confidential. Any activity performed from your account is your responsibility. GBA may suspend or delete an account in case of abuse, fraud, or violation of these terms.',
    'terms_of_service_section3_title': '3. Orders and payment',
    'terms_of_service_section3_body':
        'Orders are subject to stock availability. Prices displayed are in FCFA and include applicable taxes. GBA accepts payments via mobile money and bank cards (Stripe). Any confirmed order commits the customer. Refunds in case of cancellation are subject to the return policy in effect.',
    'terms_of_service_section4_title': '4. Delivery',
    'terms_of_service_section4_body':
        'Delivery times are indicative and may vary depending on the area and courier availability. GBA is not responsible for delays due to external causes (weather, exceptional events). Make sure you provide an accurate delivery address.',
    'terms_of_service_section4_body_location':
        'Geolocation is used only to facilitate delivery. It is enabled only after your explicit consent and is never collected in the background.',
    'terms_of_service_section5_title': '5. Support',
    'terms_of_service_section5_body':
        'For any questions, complaints or refund requests, contact our support via the in-app chat or by email. GBA aims to respond within 48 business hours. Any dispute is subject to the competent jurisdiction.',
    'access_blocked': 'Access blocked',
    'account_suspended': 'Account suspended',
    'suspension_reason': 'Suspension reason',
    'what_to_do_now': 'What to do now',
    'greeting_morning': 'Good morning',
    'greeting_afternoon': 'Good afternoon',
    'greeting_evening': 'Good evening',
    'auth_label_email': 'Email address',
    'auth_label_password': 'Password',
    'auth_label_full_name': 'Full name',
    'auth_label_confirm_password': 'Confirm password',
    'auth_forgot_password_link': 'Forgot password?',
    'auth_login_button': 'Sign in',
    'auth_no_account_yet': 'No account yet? ',
    'auth_sign_up_link': 'Sign up',
    'auth_already_have_account': 'Already have an account? ',
    'auth_enter_email': 'Enter your email',
    'auth_invalid_email_format': 'Invalid email format',
    'auth_enter_password': 'Enter your password',
    'auth_min_6_chars': 'Minimum 6 characters',
    'auth_enter_full_name': 'Enter your full name',
    'auth_enter_a_password': 'Enter a password',
    'auth_min_8_chars': 'Minimum 8 characters',
    'auth_confirm_your_password': 'Confirm your password',
    'auth_at_least_1_upper': 'At least 1 uppercase required',
    'auth_at_least_1_digit': 'At least 1 digit required',
    'auth_at_least_1_special': 'At least 1 special character required',
    'auth_resend_confirmation': 'Resend confirmation email →',
    'auth_resend_confirmation_sent': 'Confirmation email resent.',
    'auth_error_invalid_credentials': 'Sign-in denied. Check your password or confirm your email (check your inbox).',
    'auth_error_server_db': 'Server error while creating account. Try again. If it persists, contact support.',
    'auth_error_email_exists': 'This email is already registered. Sign in or use “Forgot password”.',
    'auth_error_email_invalid': 'Invalid email. Re-enter your email (no spaces/invisible characters) and try again.',
    'auth_error_generic': 'An error occurred. Please try again.',
    'auth_check_your_email': 'Check your email',
    'auth_confirmation_sent_to': 'A confirmation link was sent to\n{email}',
    'auth_resend_email_button': 'Resend email',
    'auth_go_to_login': 'Go to sign in',
    'auth_forgot_password_instruction_short': 'Enter your email to receive a reset link',
    'auth_send_link': 'Send link',
    'auth_email_sent': 'Email sent!',
    'auth_reset_link_sent_to': 'A reset link was sent to\n{email}',
    'auth_check_spam': 'Remember to check your spam folder.',
    'auth_back_to_login': 'Back to sign in',
    'remember_me': 'Remember me',
    'auth_strength_very_weak': 'Very weak',
    'auth_strength_weak': 'Weak',
    'auth_strength_medium': 'Medium',
    'auth_strength_strong': 'Strong',
    'auth_criterion_chars': '≥ 8 chars',
    'auth_criterion_upper': 'Upper',
    'auth_criterion_digit': 'Digit',
    'auth_criterion_special': 'Special',
    'auth_verify_email_title': 'Verify your email',
    'auth_reset_link_sent': 'A reset link was sent to\n{email}',
    'login_required_title': 'Login required',
    'login_required_message': 'Log in or create an account to access this feature.',
    'login_required': 'Login required',
    'browse_without_account': 'Browse without account',
    'no_internet_connection': 'No internet connection',
    'check_connection_and_retry': 'Check your connection and try again',
    'connection_error': 'Connection error. Check your internet connection.',
    'create_order': 'Create Order',
    'cash_on_delivery': 'Cash on delivery',
    'location_services_disabled': 'Location services disabled',
    'enable_location_to_continue': 'Enable location services to continue',
    'open_settings': 'Open settings',
    'location_permission_denied': 'Location permission denied',
    'location_permission_required': 'Location permission is required for this feature',
    'location_permission_permanently_denied': 'Location permission permanently denied. Please enable it in settings.',
    'welcome': 'Welcome',
    'skip': 'Skip',
    'percent_completed': '{percent}% completed',
    'finish': 'Finish',
    'next': 'Next',
    'complete_profile': 'Complete your profile',
    'profile_info_speeds_checkout': 'This information speeds up checkout and delivery.',
    'choose_app_language': 'Choose the app language.',
    'choose_what_to_receive': 'Choose what you want to receive.',
    'enable_notifications': 'Enable notifications',
    'orders_notifications': 'Orders',
    'promotions_notifications': 'Promotions',
    'messages_notifications': 'Messages',
  };

  // Translations for French
  late final Map<String, String> _frenchTranslations = {
    'appName': 'Client e-commerce',
    'flutter_works': 'Flutter fonctionne !',
    'app_compiled_successfully': 'Application compilée avec succès',
    'driver_app_title': 'GBA Livreur',
    'driver_login_subtitle': 'Connectez-vous pour accéder à vos livraisons',
    'driver_email_label': 'Email professionnel',
    'driver_email_required': 'Entrez votre email',
    'driver_email_invalid': 'Email invalide',
    'driver_password_label': 'Mot de passe',
    'driver_password_required': 'Entrez votre mot de passe',
    'driver_password_min': '6 caractères minimum',
    'driver_login_button': 'Se connecter',
    'welcome_to_store': 'Bienvenue sur {store}',
    'choose_option_to_continue': 'Choisissez une option pour continuer',
    'splash_welcome_full': 'Bienvenue sur Global Business Amdaradir',
    'brand_full_name': 'Global Business Amdaradir',
    'login': 'Connexion',
    'register': 'Inscription',
    'create_account': 'Créer un compte',
    'accept_legal_prefix': "J'accepte les ",
    'accept_legal_and': ' et la ',
    'already_have_account': 'Vous avez déjà un compte ?',
    'register_accept_legal_required':
        "Veuillez accepter les Conditions d'utilisation et la Politique de confidentialité.",
    'register_account_created_check_email':
        "Compte créé. Vérifiez votre e-mail puis connectez-vous.",
    'auth_login_title': 'Connexion',
    'auth_login_subtitle': 'Bienvenue sur Global Business Amdaradir',
    'auth_register_title': 'Créer un compte',
    'auth_register_subtitle': 'Rejoignez Global Business Amdaradir',
    'cgu': 'Conditions d\'utilisation',
    'confidentiality': 'Politique de confidentialité',
    'conversation_priority_urgent': 'Urgent',
    'conversation_priority_high': 'Élevée',
    'conversation_priority_normal': 'Normale',
    'conversation_priority_low': 'Faible',
    'privacy_policy_section1_title': '1. Données collectées',
    'privacy_policy_section1_body':
        "GBA collecte les informations nécessaires à la création de votre compte et au traitement de vos commandes : nom, prénom, adresse e-mail, numéro de téléphone, adresse de livraison et historique de commandes. Ces données sont stockées de manière sécurisée via Supabase (serveurs chiffrés). Aucune donnée bancaire n'est conservée sur nos serveurs.",
    'privacy_policy_section2_title': '2. Utilisation des données',
    'privacy_policy_section2_body':
        'Vos données servent à : authentification et sécurisation de votre compte, traitement et suivi de vos commandes, communication (notifications de statut de commande, promotions avec votre accord), amélioration du service via des statistiques anonymisées, prévention de la fraude.',
    'privacy_policy_section2_body_location':
        "Si vous utilisez la fonctionnalité de géolocalisation, votre position est utilisée uniquement pour faciliter la livraison. Elle n'est demandée qu'après votre accord explicite et n'est jamais collectée en arrière-plan.",
    'privacy_policy_section3_title': '3. Notifications push',
    'privacy_policy_section3_body':
        "Si vous autorisez les notifications, un identifiant (token Firebase) est utilisé pour vous envoyer des alertes liées à vos commandes, livraisons, messages et promotions. Vous pouvez désactiver les notifications à tout moment dans les paramètres de l'application.",
    'privacy_policy_section4_title': '4. Partage et conservation',
    'privacy_policy_section4_body':
        "Nous ne vendons jamais vos données. Elles peuvent être partagées avec nos livreurs partenaires dans le seul but d'assurer la livraison. Les données sont conservées pendant la durée de votre compte, puis supprimées sur demande. Services tiers utilisés : Supabase (base de données), Firebase (notifications), Stripe / services de paiement mobile (paiements).",
    'privacy_policy_section5_title': '5. Vos droits',
    'privacy_policy_section5_body':
        "Vous avez le droit d'accéder, de corriger ou de supprimer vos données personnelles. Pour exercer ces droits ou pour toute question relative à la confidentialité, contactez-nous via le support dans l'application. Conformité avec les lois en vigueur au Tchad et aux standards internationaux de protection des données.",
    'terms_of_service_section1_title': '1. Objet et acceptation',
    'terms_of_service_section1_body':
        "Les présentes Conditions Générales d'Utilisation (CGU) régissent l'utilisation de l'application mobile GBA (« Global Business Amdaradir »), disponible sur Android et iOS. En créant un compte ou en passant une commande, vous acceptez intégralement ces CGU. GBA se réserve le droit de les modifier à tout moment ; les changements prennent effet dès leur publication.",
    'contact_title': 'Contact',
    'contact_phone_title': 'Téléphone',
    'contact_facebook_title': 'Facebook',
    'contact_facebook_subtitle': 'Ouvrir notre page Facebook',
    'contact_tiktok_title': 'TikTok',
    'contact_tiktok_subtitle': 'Ouvrir notre profil TikTok',
    'contact_open_failed': "Impossible d'ouvrir le lien.",
    'terms_of_service_section2_title': '2. Compte utilisateur',
    'terms_of_service_section2_body':
        "Vous devez fournir des informations exactes lors de l'inscription. Vous êtes seul responsable de la confidentialité de vos identifiants. Toute activité effectuée depuis votre compte est de votre responsabilité. GBA peut suspendre ou supprimer tout compte en cas d'utilisation abusive, de fraude ou de violation des présentes CGU.",
    'terms_of_service_section3_title': '3. Commandes et paiement',
    'terms_of_service_section3_body':
        "Les commandes sont soumises à la disponibilité des stocks. Les prix affichés sont en FCFA, TVA incluse. GBA accepte les paiements via Moov Money, Orange Money et carte bancaire (Stripe). Toute commande validée engage le client. Le remboursement en cas d'annulation est soumis à la politique de retour en vigueur.",
    'terms_of_service_section4_title': '4. Livraison',
    'terms_of_service_section4_body':
        "Les délais de livraison sont indicatifs et peuvent varier selon la zone géographique et la disponibilité des livreurs. GBA décline toute responsabilité pour les retards dus à des causes extérieures (intémpéries, événements exceptionnels). Assurez-vous de fournir une adresse de livraison précise.",
    'terms_of_service_section4_body_location':
        "La géolocalisation est utilisée uniquement pour faciliter la livraison. Elle n'est activée qu'après votre accord explicite et n'est jamais collectée en arrière-plan.",
    'terms_of_service_section5_title': '5. Support et réclamations',
    'terms_of_service_section5_body':
        "Pour toute question, réclamation ou demande de remboursement, contactez notre support directement via le chat de l'application ou par e-mail. GBA s'engage à répondre dans un délai de 48 heures ouvrables. Tout litige est soumis à la juridiction compétente.",
    // ── Clés complémentaires (alignement avec l’anglais) ──
    'home': 'Accueil',
    'categories': 'Catégories',
    'cart': 'Panier',
    'orders': 'Commandes',
    'profile': 'Profil',
    'view': 'Voir',
    'delete': 'Supprimer',
    'points': 'Points',
    'first_name': 'Prénom',
    'last_name': 'Nom',
    'bio': 'Bio',
    'postal_code': 'Code postal',
    'not_provided': 'Non renseigné',
    'profile_completion_title': 'Complétion du profil',
    'profile_completion_hint': 'Complétez votre profil pour accélérer la commande.',
    'complete_now': 'Compléter maintenant',
    'profile_tab_info': 'Infos',
    'profile_tab_edit': 'Modifier',
    'personal_information': 'Informations personnelles',
    'profile_photo': 'Photo de profil',
    'cover_photo': 'Photo de couverture',
    'choose_cover': 'Choisir une couverture',
    'choose_photo': 'Choisir une photo',
    'camera': 'Appareil photo',
    'gallery': 'Galerie',
    'photo_updated_success': 'Photo mise à jour avec succès !',
    'photo_update_error': 'Erreur lors de la mise à jour de la photo',
    'profile_updated_success': 'Profil mis à jour avec succès !',
    'fill_required_fields': 'Veuillez remplir tous les champs obligatoires',
    'invalid_phone_number': 'Numéro de téléphone invalide',
    'quick_actions': 'Actions rapides',
    'specialOrder': 'Commande spéciale',
    'messaging': 'Messagerie',
    'settings': 'Paramètres',
    'language': 'Langue',
    'helpSupport': 'Aide et support',
    'admin_support_available': 'Service client disponible',
    'user_not_logged_in': 'Utilisateur non connecté',
    'email': 'E-mail',
    'password': 'Mot de passe',
    'forgotPassword': 'Mot de passe oublié ?',
    'forgot_password_title': 'Mot de passe oublié',
    'forgot_password_instruction':
        'Entrez votre e-mail. Nous vous enverrons un lien pour définir un nouveau mot de passe.',
    'forgot_password_send_link': 'Envoyer le lien',
    'forgot_password_email_sent': 'E-mail envoyé. Vérifiez votre boîte de réception (et les spams).',
    'reset_password_instruction': 'Définissez votre nouveau mot de passe.',
    'validate': 'Valider',
    'search': 'Rechercher',
    'popularProducts': 'Produits populaires',
    'addToCart': 'Ajouter au panier',
    'checkout': 'Commander',
    'total': 'Total',
    'confirmOrder': 'Confirmer la commande',
    'orderHistory': 'Historique des commandes',
    'trackOrder': 'Suivre la commande',
    'uploadImage': 'Télécharger une image',
    'productName': 'Nom du produit',
    'quantity': 'Quantité',
    'description': 'Description',
    'send': 'Envoyer',
    'message': 'Message',
    'cart_empty': 'Votre panier est vide',
    'notification_default_title': 'Notification',
    'open': 'Ouvrir',
    'push_title_order_status': 'Mise à jour de commande',
    'push_title_cart_abandoned': 'Rappel panier',
    'push_title_promotion': 'Promotion',
    'push_body_order_status': 'Commande{orderLabel} : {status}',
    'push_order_status_default_status': 'mise à jour',
    'push_body_cart_abandoned_with_count': 'Vous avez {count} article(s) dans votre panier.',
    'push_body_cart_abandoned': 'Vous avez des articles dans votre panier.',
    'push_body_promotion': 'Découvrez nos offres.',
    'order_status_pending': 'En attente',
    'order_status_confirmed': 'Confirmée',
    'order_status_shipped': 'Expédiée',
    'order_status_delivered': 'Livrée',
    'order_status_cancelled': 'Annulée',
    'order_status_refunded': 'Remboursée',
    'menu': 'Menu',
    'favorites': 'Favoris',
    'promotions': 'Promotions',
    'chat': 'Chat',
    'logout': 'Déconnexion',
    'refresh': 'Actualiser',
    'retry': 'Réessayer',
    'clear_filter': 'Effacer le filtre',
    'discover': 'Découvrir',
    'discover_products': 'Découvrez nos produits',
    'continue_shopping': 'Continuer les achats',
    'products': 'Produits',
    'my_orders_title': 'Mes commandes',
    'orders_total_count': '{count} commande(s) au total',
    'no_orders': 'Aucune commande',
    'no_orders_hint': 'Vos commandes apparaîtront ici',
    'order_details_title': 'Détails de la commande',
    'order_information': 'Informations',
    'name': 'Nom',
    'phone': 'Téléphone',
    'country': 'Pays',
    'city': 'Ville',
    'district': 'Quartier',
    'address': 'Adresse',
    'number': 'Numéro',
    'date': 'Date',
    'payment': 'Paiement',
    'customer': 'Client',
    'shipping_address_title': 'Adresse de livraison',
    'items': 'Articles',
    'no_items': 'Aucun article',
    'subtotal': 'Sous-total',
    'not_available': 'N/D',
    'unknown': 'Inconnu',
    'order_status_processing': 'En cours',
    'added_to_favorites': '{name} ajouté aux favoris',
    'leave_review': 'Laisser un avis',
    'edit_my_review': 'Modifier mon avis',
    'edit': 'Modifier',
    'review_comment_optional': 'Commentaire (optionnel)',
    'review_submitted_bonus': 'Avis envoyé. +5 points ajoutés',
    'review_error_with_details': 'Erreur d\'avis : {error}',
    'product_not_found': 'Produit introuvable',
    'view_cart': 'Voir le panier',
    'in_stock_with_count': 'En stock ({count})',
    'no_description_available': 'Aucune description disponible',
    'reviews': 'Avis',
    'no_reviews_yet': 'Aucun avis pour le moment',
    'similar_products': 'Produits similaires',
    'items_count': '{count} article(s)',
    'delivery': 'Livraison',
    'out_of_stock': 'Rupture de stock',
    'recommended_for_you': 'Recommandé pour vous',
    'our_products': 'Nos produits',
    'search_products_hint': 'Que recherchez-vous ?',
    'no_products_available': 'Aucun produit disponible',
    'no_products_in_category': 'Aucun produit dans cette catégorie',
    'limited_offers_discounts': 'Offres et réductions limitées',
    'featured': 'À la une',
    'pull_to_refresh': 'Tirez pour actualiser',
    'no_featured': 'Aucun article à la une pour le moment',
    'no_promotions': 'Aucune promotion pour le moment',
    'no_favorites': 'Aucun favori',
    'favorites_empty_hint': 'Ajoutez vos produits favoris ici',
    'explore_products': 'Explorer les produits',
    'collections': 'Collections',
    'shared': 'Partagé',
    'sort_recent': 'Récent',
    'sort_name': 'Nom',
    'sort_price_asc': 'Prix ↑',
    'sort_price_desc': 'Prix ↓',
    'messages': 'Messages',
    'support_assistance': 'Support et assistance',
    'search_conversation_hint': 'Rechercher une conversation...',
    'no_conversation': 'Aucune conversation',
    'start_new_conversation': 'Démarrer une nouvelle conversation',
    'conversation_number': 'Conversation n°{id}',
    'no_message': 'Aucun message',
    'yesterday': 'Hier',
    'now': 'Maintenant',
    'day_short': 'j',
    'hour_short': 'h',
    'minute_short': 'min',
    'filter': 'Filtrer',
    'filter_categories': 'Filtrer les catégories',
    'all': 'Tout',
    'popular': 'Populaire',
    'new': 'Nouveau',
    'cancel': 'Annuler',
    'authorize': 'Autoriser',
    'notification_permission_rationale':
        'Autorisez GBA à vous envoyer des notifications pour vos commandes, livraisons et promotions. Vous pouvez les désactiver à tout moment dans les paramètres.',
    'apply': 'Appliquer',
    'press_back_again_to_exit': 'Appuyez à nouveau pour quitter',
    'no_results': 'Aucun résultat',
    'try_another_keyword': 'Essayez un autre mot-clé.',
    'search_category_hint': 'Rechercher une catégorie...',
    'products_count': '{count} produit(s)',
    'explore': 'Explorer',
    'no_categories': 'Aucune catégorie',
    'no_categories_hint': "Vous n'avez aucune catégorie pour le moment.",
    'error_loading': 'Erreur de chargement',
    'cart_loading': 'Chargement du panier…',
    'loading_categories': 'Chargement des catégories…',
    'category': 'Catégorie',
    'support_admin': 'Support admin',
    'my_account': 'Mon compte',
    'navigation': 'Navigation',
    'special_orders': 'Commandes spéciales',
    'new_special_order': 'Nouvelle commande spéciale',
    'my_special_orders': 'Mes commandes spéciales',
    'special_order_empty_title': 'Aucune commande spéciale pour le moment',
    'special_order_create_button': 'Créer une commande spéciale',
    'special_order_generic_title': 'Commande spéciale',
    'special_order_loading_error_with_details': 'Erreur de chargement : {error}',
    'special_order_shipping_air': 'Avion',
    'special_order_shipping_standard': 'Standard',
    'special_order_quantity_delivery': 'Quantité : {qty}  •  Livraison : {shipping}',
    'special_order_quote_with_amount': 'Devis : {amount}',
    'special_order_quote_pending': 'En attente de devis',
    'special_order_eta_with_range': 'Arrivée prévue : {range}',
    'special_order_quote_status_with_status': 'Statut du devis : {status}',
    'special_order_details_title': 'Détails de la commande spéciale',
    'special_order_not_found': 'Commande spéciale introuvable',
    'special_order_status_with_status': 'Statut : {status}',
    'special_order_accept_quote': 'Accepter',
    'special_order_reject_quote': 'Refuser',
    'special_order_negotiate_quote': 'Négocier (contre-proposition)',
    'special_order_history': 'Historique',
    'special_order_timeline': 'Chronologie',
    'special_order_offers_messages': 'Offres / messages',
    'special_order_quote_accepted': 'Devis accepté',
    'special_order_quote_rejected': 'Devis refusé',
    'special_order_counter_offer_sent': 'Contre-proposition envoyée',
    'special_order_reject_dialog_title': 'Refuser le devis',
    'special_order_counter_dialog_title': 'Faire une contre-proposition',
    'special_order_unit_price_label': 'Prix unitaire proposé',
    'special_order_shipping_fee_label': 'Frais de livraison proposés',
    'special_order_optional_message_label': 'Message (optionnel)',
    'special_order_invalid_unit_price': 'Prix unitaire invalide',
    'special_order_quote': 'Devis',
    'special_order_subtotal': 'Sous-total',
    'special_order_shipping': 'Livraison',
    'special_order_tax': 'TVA',
    'special_order_service_fee': 'Service',
    'special_order_total': 'Total',
    'special_order_valid_until_with_date': 'Valable jusqu\'au : {date}',
    'special_order_step_indicator': 'Étape {current}/{total}',
    'special_order_step_details': 'Détails',
    'special_order_step_images': 'Photos',
    'special_order_step_delivery': 'Livraison',
    'special_order_step_summary': 'Résumé',
    'save_and_continue': 'Enregistrer et continuer',
    'back': 'Retour',
    'special_order_product_details_title': 'Détails du produit',
    'special_order_product_name_required': 'Le nom du produit est obligatoire',
    'special_order_invalid_quantity': 'Quantité invalide',
    'special_order_description_required': 'La description est obligatoire',
    'special_order_images_optional_title': 'Photos (optionnel)',
    'special_order_add': 'Ajouter',
    'special_order_images_hint': 'Ajoutez des photos pour identifier le produit.',
    'special_order_delivery_title': 'Livraison',
    'special_order_location_ready_with_accuracy': 'Position enregistrée (±{meters}m)',
    'special_order_use_my_location': 'Utiliser ma position',
    'special_order_detecting_location': 'Détection de votre position...',
    'special_order_location_not_available': 'Position non disponible',
    'special_order_shipping_method': 'Mode de livraison',
    'special_order_shipping_air_fast': 'Par avion (plus rapide)',
    'special_order_shipping_other_standard': 'Autre (standard)',
    'special_order_notes_optional': 'Notes (optionnel)',
    'special_order_notes_hint': 'Détails, liens, etc.',
    'special_order_summary_title': 'Récapitulatif',
    'special_order_summary_product': 'Produit',
    'special_order_summary_quantity': 'Quantité',
    'special_order_summary_delivery': 'Livraison',
    'special_order_summary_images': 'Images',
    'special_order_summary_notes': 'Notes',
    'special_order_summary_description': 'Description',
    'special_order_gps_required_before_continue':
        'Activez le GPS et enregistrez votre position avant de continuer.',
    'special_order_gps_required_submit':
        'La localisation GPS est obligatoire pour envoyer cette commande spéciale.',
    'no_internet_connection_title': 'Pas de connexion internet',
    'no_internet_connection_message': 'Vérifiez votre réseau puis réessayez.',
    'notification_body_audio_message': 'Message vocal',
    'notification_body_image_message': 'Image',
    'notification_body_new_message': 'Nouveau message',
    'special_order_gps_location': 'Localisation GPS',
    'special_order_confirm_hint':
        'En confirmant, votre demande sera envoyée à l\'équipe pour traitement.',
    'special_order_location_optional': 'Position non disponible',
    'special_order_description': 'Description',
    'special_order_check_required_fields': 'Veuillez vérifier les champs obligatoires',
    'special_order_sent': 'Commande spéciale envoyée',
    'special_order_send_error': 'Erreur d\'envoi',
    'special_order_draft_restored': 'Brouillon restauré',
    'special_order_geolocation_mobile_only': 'La géolocalisation est disponible sur mobile.',
    'special_order_enable_location_services': 'Activez la localisation pour continuer.',
    'special_order_location_permission_denied': 'Permission de localisation refusée.',
    'special_order_location_saved_with_accuracy': 'Position enregistrée (±{meters}m)',
    'special_order_location_failed_with_details': 'Impossible d\'obtenir la position : {error}',
    'special_order_max_images': 'Maximum {count} image(s)',
    'special_order_max_images_ignored': 'Maximum {count} image(s) (les autres ont été ignorées)',
    'special_order_image_too_large_with_size': 'Image trop volumineuse ({size} Mo)',
    'special_order_pick_images_error_with_details': 'Erreur lors du choix des images : {error}',
    'special_order_status_pending': 'En attente',
    'special_order_status_quoted': 'Devis reçu',
    'special_order_status_countered': 'Contre-proposé',
    'special_order_status_accepted': 'Accepté',
    'special_order_status_rejected': 'Refusé',
    'no_events_yet': 'Aucun événement pour le moment',
    'personalization_gift': 'Personnalisation / Cadeau',
    'coming_soon': '{label} : bientôt disponible',
    'favorites_not_found_title': 'Produits favoris introuvables',
    'favorites_not_found_hint': 'Rechargez la liste des produits.',
    'product': 'Produit',
    'removed_from_cart': '{name} retiré du panier',
    'removed_from_favorites': '{name} retiré des favoris',
    'unnamed_product': 'Produit sans nom',
    'no_brand': 'Sans marque',
    'my_collections': 'Mes collections',
    'create_collection': 'Créer une collection',
    'collection_summer_2024': 'Été 2024',
    'collection_essentials': 'Essentiels',
    'collection_gifts': 'Cadeaux',
    'store_name': 'GBA Store',
    'loading_products': 'Chargement des produits…',
    'register_subtitle_join_store': 'Rejoignez GBA Store en 30 secondes',
    'full_name': 'Nom complet',
    'enter_your_name': 'Veuillez entrer votre nom',
    'enter_your_password': 'Veuillez entrer votre mot de passe',
    'confirm_your_password': 'Veuillez confirmer votre mot de passe',
    'password_min_length_register': 'Le mot de passe doit contenir au moins 6 caractères.',
    'see_all': 'Voir tout',
    'error_loading_with_details': 'Erreur de chargement : {error}',
    'added_to_cart': '{name} ajouté au panier',
    'page_not_found_title': 'Page introuvable',
    'no_route_for': 'Aucune route pour : {route}',
    'back_to_home': 'Retour à l\'accueil',
    'ad_mega_sale_title': '🎫 MEGA SOLDES -50 %',
    'ad_mega_sale_subtitle': 'Sur tous les smartphones',
    'ad_free_delivery_title': '🚚 Livraison gratuite',
    'ad_free_delivery_subtitle': 'Pour toute commande de plus de 100 €',
    'ad_flash_deal_title': '⚡ Offre flash',
    'ad_flash_deal_subtitle': 'Nouvelles offres chaque jour',
    'ad_promo_code_title': '🎁 Code promo : SAVE20',
    'ad_promo_code_subtitle': '20 % de réduction immédiate',
    'notifications': 'Notifications',
    'appearance': 'Apparence',
    'privacy': 'Confidentialité',
    'danger_zone': 'Zone dangereuse',
    'push_notifications': 'Notifications push',
    'receive_notifications': 'Recevoir les notifications',
    'notification_preferences': 'Préférences de notifications',
    'choose_categories': 'Choisir les catégories',
    'sounds': 'Sons',
    'enable_sound_effects': 'Activer les effets sonores',
    'vibrations': 'Vibrations',
    'haptic_feedback': 'Retour haptique',
    'dark_mode': 'Mode sombre',
    'enable_dark_theme': 'Activer le thème sombre',
    'app_language': 'Langue de l\'app',
    'language_french': 'Français',
    'language_english': 'Anglais',
    'language_arabic': 'Arabe',
    'change_password': 'Changer le mot de passe',
    'change_password_subtitle': 'Mettre à jour votre mot de passe',
    'privacy_policy': 'Politique de confidentialité',
    'privacy_policy_subtitle': 'Comment nous protégeons vos données',
    'terms_of_service': 'Conditions d\'utilisation',
    'terms_of_service_subtitle': 'Lire les conditions',
    'clear_cache': 'Vider le cache',
    'cache_cleared_success': 'Cache vidé avec succès',
    'logout_confirm_message': 'Voulez-vous vraiment vous déconnecter ?',
    'enable_disable_all_notifications': 'Activer / Désactiver toutes les notifications',
    'notification_category_orders_subtitle': 'Statut des commandes, livraison, annulation',
    'notification_category_promotions_subtitle': 'Offres, réductions, nouveautés',
    'notification_category_messages_subtitle': 'Nouveaux messages support / chat',
    'save': 'Enregistrer',
    'change_password_security_hint': 'Pour votre sécurité, confirmez votre mot de passe actuel.',
    'current_password': 'Mot de passe actuel',
    'new_password': 'Nouveau mot de passe',
    'confirm_password': 'Confirmer le mot de passe',
    'error_user_email_not_found': 'Impossible de continuer : e-mail utilisateur introuvable.',
    'password_min_length': 'Le nouveau mot de passe doit contenir au moins 6 caractères.',
    'passwords_do_not_match': 'Les mots de passe ne correspondent pas.',
    'password_changed_success': 'Mot de passe modifié.',
    'error_with_details': 'Erreur : {error}',
    'share_unavailable_with_details': 'Partage impossible : {error}',
    'link_copied': 'Lien copié',
    'image_saved_to_gallery': 'Image enregistrée dans la galerie',
    'open_link_unavailable': 'Impossible d\'ouvrir le lien',
    'image': 'Image',
    'download': 'Télécharger',
    'share': 'Partager',
    'view_fullscreen': 'Voir en plein écran',
    'copy_link': 'Copier le lien',
    'chat_error_sending_with_details': 'Erreur d\'envoi : {error}',
    'chat_error_sending_image_with_details': 'Erreur d\'envoi d\'image : {error}',
    'image_upload_failed': 'Échec du téléchargement de l\'image',
    'support_client': 'Support client',
    'order_number': 'Commande n°{id}',
    'order_number_label': 'N° de commande',
    'track_order': 'Suivre la commande',
    'order_tracking_title': 'Suivi de commande',
    'search_product_hint': 'Que recherchez-vous ?',
    'search_history': 'Recherches récentes',
    'search_clear_history': 'Effacer',
    'price': 'Prix',
    'reset': 'Réinitialiser',
    'filter_min_rating': 'Note minimum',
    'order_cancelled': 'Commande annulée',
    'current': 'Actuel',
    'permission_denied': 'Permission refusée',
    'start_conversation': 'Démarrer la conversation',
    'we_are_here_to_help': 'Nous sommes là pour vous aider',
    'type_your_message': 'Tapez votre message...',
    'conversation_info_title': 'Informations sur la conversation',
    'label_id': 'ID',
    'label_status': 'Statut',
    'label_priority': 'Priorité',
    'label_order': 'Commande',
    'label_created_at': 'Créé le',
    'today': 'Aujourd\'hui',
    'conversation_status_active': 'Active',
    'conversation_status_resolved': 'Résolue',
    'conversation_status_archived': 'Archivée',
    'conversation_status_pending': 'En attente',
    'access_blocked': 'Accès bloqué',
    'account_suspended': 'Compte suspendu',
    'suspension_reason': 'Motif de la suspension',
    'what_to_do_now': 'Que faire maintenant ?',
    'contact_support_error': 'Si vous pensez qu\'il s\'agit d\'une erreur, contactez le support.',
    'greeting_morning': 'Bonjour',
    'greeting_afternoon': 'Bon après-midi',
    'greeting_evening': 'Bonsoir',
    'auth_label_email': 'Adresse email',
    'auth_label_password': 'Mot de passe',
    'auth_label_full_name': 'Nom complet',
    'auth_label_confirm_password': 'Confirmer le mot de passe',
    'auth_forgot_password_link': 'Mot de passe oublié ?',
    'auth_login_button': 'Se connecter',
    'auth_no_account_yet': 'Pas encore de compte ? ',
    'auth_sign_up_link': "S'inscrire",
    'auth_already_have_account': 'Déjà un compte ? ',
    'auth_enter_email': 'Entrez votre email',
    'auth_invalid_email_format': 'Format email invalide',
    'auth_enter_password': 'Entrez votre mot de passe',
    'auth_min_6_chars': 'Minimum 6 caractères',
    'auth_enter_full_name': 'Entrez votre nom complet',
    'auth_enter_a_password': 'Entrez un mot de passe',
    'auth_min_8_chars': 'Minimum 8 caractères',
    'auth_confirm_your_password': 'Confirmez votre mot de passe',
    'auth_at_least_1_upper': 'Au moins 1 majuscule requise',
    'auth_at_least_1_digit': 'Au moins 1 chiffre requis',
    'auth_at_least_1_special': 'Au moins 1 caractère spécial requis',
    'auth_resend_confirmation': 'Renvoyer l\'email de confirmation →',
    'auth_resend_confirmation_sent': 'Email de confirmation renvoyé.',
    'auth_error_invalid_credentials': 'Connexion refusée. Vérifie le mot de passe OU confirme ton email (regarde ta boîte mail).',
    'auth_error_server_db': 'Erreur serveur lors de la création du compte. Réessaie. Si ça persiste, contacte le support.',
    'auth_error_email_exists': 'Cet email existe déjà. Connecte-toi ou utilise « Mot de passe oublié ».',
    'auth_error_email_invalid': 'Email invalide. Retape l\'email (sans espaces/caractères invisibles) et réessaie.',
    'auth_error_generic': 'Une erreur s\'est produite. Réessaie.',
    'auth_check_your_email': 'Vérifiez votre email',
    'auth_confirmation_sent_to': 'Un lien de confirmation a été envoyé à\n{email}',
    'auth_resend_email_button': 'Renvoyer l\'email',
    'auth_go_to_login': 'Aller à la connexion',
    'auth_forgot_password_instruction_short': 'Entrez votre email pour recevoir un lien de réinitialisation',
    'auth_send_link': 'Envoyer le lien',
    'auth_email_sent': 'Email envoyé !',
    'auth_reset_link_sent_to': 'Un lien de réinitialisation a été envoyé à\n{email}',
    'auth_check_spam': 'Pensez à vérifier vos spams.',
    'auth_back_to_login': 'Retour à la connexion',
    'auth_strength_very_weak': 'Très faible',
    'auth_strength_weak': 'Faible',
    'auth_strength_medium': 'Moyen',
    'auth_strength_strong': 'Fort',
    'auth_criterion_chars': '≥ 8 car.',
    'auth_criterion_upper': 'Majuscule',
    'auth_criterion_digit': 'Chiffre',
    'auth_criterion_special': 'Spécial',
    'auth_verify_email_title': 'Vérifiez votre email',
    'auth_reset_link_sent': 'Un lien de réinitialisation a été envoyé à\n{email}',
    'remember_me': 'Se souvenir de moi',
    'login_required_title': 'Connexion requise',
    'login_required_message': 'Connectez-vous ou créez un compte pour accéder à cette fonctionnalité.',
    'login_required': 'Connexion requise',
    'browse_without_account': 'Regarder sans compte',
    'no_internet_connection': 'Pas de connexion internet',
    'check_connection_and_retry': 'Vérifiez votre connexion et réessayez',
    'connection_error': 'Erreur de connexion. Vérifiez votre connexion internet.',
    'create_order': 'Créer une commande',
    'cash_on_delivery': 'Paiement à la livraison',
    'location_services_disabled': 'Services de localisation désactivés',
    'enable_location_to_continue': 'Activez les services de localisation pour continuer',
    'open_settings': 'Ouvrir les paramètres',
    'location_permission_denied': 'Permission de localisation refusée',
    'location_permission_required': 'La permission de localisation est requise pour cette fonctionnalité',
    'location_permission_permanently_denied': 'Permission de localisation refusée définitivement. Veuillez l\'activer dans les paramètres.',
    'welcome': 'Bienvenue',
    'skip': 'Passer',
    'percent_completed': '{percent}% complété',
    'finish': 'Terminer',
    'next': 'Suivant',
    'complete_profile': 'Complète ton profil',
    'profile_info_speeds_checkout': 'Ces informations accélèrent le checkout et la livraison.',
    'choose_app_language': 'Choisis la langue de l\'application.',
    'choose_what_to_receive': 'Choisis ce que tu veux recevoir.',
    'enable_notifications': 'Activer les notifications',
    'orders_notifications': 'Commandes',
    'promotions_notifications': 'Promotions',
    'messages_notifications': 'Messages',
  };

  // Translations for Arabic
  late final Map<String, String> _arabicTranslations = {
    'appName': 'عميل التجارة الإلكترونية',
    'flutter_works': 'Flutter يعمل!',
    'app_compiled_successfully': 'تم تجميع التطبيق بنجاح',
    'driver_app_title': 'سائق GBA',
    'driver_login_subtitle': 'سجّل الدخول للوصول إلى عمليات التوصيل',
    'driver_email_label': 'البريد المهني',
    'driver_email_required': 'أدخل بريدك الإلكتروني',
    'driver_email_invalid': 'بريد إلكتروني غير صالح',
    'driver_password_label': 'كلمة المرور',
    'driver_password_required': 'أدخل كلمة المرور',
    'driver_password_min': '6 أحرف على الأقل',
    'driver_login_button': 'تسجيل الدخول',
    'welcome_to_store': 'مرحبًا بك في {store}',
    'choose_option_to_continue': 'اختر خيارًا للمتابعة',
    'splash_welcome_full': 'مرحبًا بك في الأعمال العالمية أمدرادير',
    'login': 'تسجيل الدخول',
    'register': 'إنشاء حساب',
    'create_account': 'إنشاء حساب',
    'accept_legal_prefix': 'أوافق على ',
    'accept_legal_and': ' و ',
    'already_have_account': 'لديك حساب بالفعل؟',
    'register_accept_legal_required': 'يرجى الموافقة على شروط الاستخدام وسياسة الخصوصية.',
    'register_account_created_check_email':
        'تم إنشاء الحساب. تحقق من بريدك الإلكتروني ثم سجّل الدخول.',
    'auth_login_title': 'تسجيل الدخول',
    'auth_login_subtitle': 'مرحبًا بك في الأعمال العالمية أمدرادير',
    'auth_register_title': 'إنشاء حساب',
    'auth_register_subtitle': 'انضم إلى الأعمال العالمية أمدرادير',
    'cgu': 'شروط الاستخدام',
    'confidentiality': 'سياسة الخصوصية',
    'brand_full_name': 'الأعمال العالمية أمدرادير',
    'contact_title': 'اتصل بنا',
    'contact_phone_title': 'الهاتف',
    'contact_facebook_title': 'فيسبوك',
    'contact_facebook_subtitle': 'فتح صفحتنا على فيسبوك',
    'contact_tiktok_title': 'تيك توك',
    'contact_tiktok_subtitle': 'فتح ملفنا على تيك توك',
    'contact_open_failed': 'تعذر فتح الرابط.',
    'conversation_priority_urgent': 'عاجل',
    'conversation_priority_high': 'مرتفعة',
    'conversation_priority_normal': 'عادية',
    'conversation_priority_low': 'منخفضة',
    'privacy_policy_section1_title': '1. البيانات التي نجمعها',
    'privacy_policy_section1_body':
        'تجمع GBA المعلومات اللازمة لإنشاء حسابك ومعالجة طلباتك: الاسم، البريد الإلكتروني، رقم الهاتف، عنوان التوصيل وسجل الطلبات. يتم تخزين هذه البيانات بشكل آمن عبر Supabase (خوادم مشفّرة). لا نقوم بتخزين بيانات بطاقتك البنكية على خوادمنا.',
    'privacy_policy_section2_title': '2. استخدام البيانات',
    'privacy_policy_section2_body':
        'تُستخدم بياناتك من أجل: المصادقة وحماية الحساب، معالجة الطلبات وتتبعها، دعم العملاء والدردشة داخل التطبيق، تحسين الخدمة عبر إحصائيات مجهولة، والوقاية من الاحتيال.',
    'privacy_policy_section2_body_location':
        'إذا استخدمت ميزات تحديد الموقع، فسيُستخدم موقعك فقط لتسهيل عملية التوصيل. لا يتم طلبه إلا بعد موافقتك الصريحة ولا يتم جمعه في الخلفية.',
    'privacy_policy_section3_title': '3. الإشعارات',
    'privacy_policy_section3_body':
        'إذا فعّلت الإشعارات، يتم استخدام رمز Firebase لإرسال تنبيهات متعلقة بالطلبات والتوصيل والرسائل والعروض. يمكنك تعطيل الإشعارات في أي وقت من إعدادات التطبيق.',
    'privacy_policy_section4_title': '4. مشاركة البيانات',
    'privacy_policy_section4_body':
        'نحن لا نبيع بياناتك أبدًا. قد تتم مشاركتها مع شركاء التوصيل فقط لإتمام عملية التوصيل. يتم الاحتفاظ بالبيانات طوال مدة حسابك ويمكن حذفها عند الطلب. خدمات الجهات الخارجية المستخدمة: Supabase (قاعدة البيانات)، Firebase (الإشعارات)، Stripe / مزوّدي الدفع عبر الهاتف (المدفوعات).',
    'privacy_policy_section5_title': '5. حقوقك',
    'privacy_policy_section5_body':
        'يمكنك طلب الوصول إلى بياناتك الشخصية أو تصحيحها أو حذفها. لممارسة هذه الحقوق أو لأي استفسار حول الخصوصية، تواصل مع الدعم عبر التطبيق.',
    'terms_of_service_section1_title': '1. الهدف',
    'terms_of_service_section1_body':
        'تنظّم شروط الاستخدام هذه استخدام تطبيق GBA (Global Business Amdaradir). عند إنشاء حساب أو إجراء طلب، فإنك توافق على هذه الشروط بالكامل. قد نقوم بتحديثها في أي وقت وتصبح التغييرات سارية بمجرد نشرها داخل التطبيق.',
    'terms_of_service_section2_title': '2. حساب المستخدم',
    'terms_of_service_section2_body':
        'يجب عليك تقديم معلومات صحيحة عند التسجيل. أنت مسؤول عن الحفاظ على سرية بيانات الدخول. أي نشاط يتم من خلال حسابك هو مسؤوليتك. يمكن لـ GBA تعليق الحساب أو حذفه في حال سوء الاستخدام أو الاحتيال أو انتهاك الشروط.',
    'terms_of_service_section3_title': '3. الطلبات والدفع',
    'terms_of_service_section3_body':
        'تخضع الطلبات لتوفر المخزون. الأسعار المعروضة بالفرنك CFA وتشمل الضرائب. تقبل GBA الدفع عبر خدمات الدفع عبر الهاتف والبطاقات البنكية (Stripe). أي طلب مؤكد يُلزم العميل. تخضع عمليات الاسترجاع في حال الإلغاء لسياسة الإرجاع المعمول بها.',
    'terms_of_service_section4_title': '4. التوصيل',
    'terms_of_service_section4_body':
        'مواعيد التوصيل تقديرية وقد تختلف حسب المنطقة وتوفر المندوبين. لا تتحمل GBA مسؤولية التأخير الناتج عن أسباب خارجية (الطقس، أحداث استثنائية). تأكد من إدخال عنوان توصيل دقيق.',
    'terms_of_service_section4_body_location':
        'يُستخدم تحديد الموقع فقط لتسهيل عملية التوصيل. لا يتم تفعيله إلا بعد موافقتك الصريحة ولا يتم جمعه في الخلفية.',
    'terms_of_service_section5_title': '5. الدعم',
    'terms_of_service_section5_body':
        'لأي استفسار أو شكوى أو طلب استرجاع، تواصل مع الدعم عبر الدردشة داخل التطبيق أو عبر البريد الإلكتروني. نسعى للرد خلال 48 ساعة عمل. أي نزاع يخضع للاختصاص القضائي المعتمد.',
    'contact_support_error': 'إذا كنت تعتقد أن هذا خطأ، يرجى الاتصال بفريق الدعم.',
    'home': 'الرئيسية',
    'categories': 'الفئات',
    'cart': 'السلة',
    'orders': 'الطلبات',
    'profile': 'الملف الشخصي',
    'view': 'عرض',
    'delete': 'حذف',
    'points': 'النقاط',
    'first_name': 'الاسم الأول',
    'last_name': 'اسم العائلة',
    'bio': 'السيرة',
    'postal_code': 'الرمز البريدي',
    'not_provided': 'غير مقدم',
    'profile_completion_title': 'إكمال الملف الشخصي',
    'profile_completion_hint': 'أكمل ملفك لتسريع الطلب.',
    'complete_now': 'أكمل الآن',
    'profile_tab_info': 'معلومات',
    'profile_tab_edit': 'تعديل',
    'personal_information': 'المعلومات الشخصية',
    'profile_photo': 'صورة الملف الشخصي',
    'cover_photo': 'صورة الغلاف',
    'choose_cover': 'اختر غلافًا',
    'choose_photo': 'اختر صورة',
    'camera': 'الكاميرا',
    'gallery': 'المعرض',
    'photo_updated_success': 'تم تحديث الصورة بنجاح!',
    'photo_update_error': 'خطأ في تحديث الصورة',
    'profile_updated_success': 'تم تحديث الملف بنجاح!',
    'fill_required_fields': 'يرجى ملء جميع الحقول المطلوبة',
    'invalid_phone_number': 'رقم هاتف غير صالح',
    'quick_actions': 'إجراءات سريعة',
    'specialOrder': 'طلب خاص',
    'messaging': 'المراسلة',
    'settings': 'الإعدادات',
    'language': 'اللغة',
    'helpSupport': 'المساعدة والدعم',
    'admin_support_available': 'خدمة العملاء متاحة',
    'user_not_logged_in': 'المستخدم غير مسجل الدخول',
    'email': 'البريد الإلكتروني',
    'password': 'كلمة المرور',
    'forgotPassword': 'نسيت كلمة المرور؟',
    'forgot_password_title': 'نسيت كلمة المرور',
    'forgot_password_instruction': 'أدخل بريدك. سنرسل لك رابطًا لتعيين كلمة مرور جديدة.',
    'forgot_password_send_link': 'إرسال الرابط',
    'forgot_password_email_sent': 'تم الإرسال. تحقق من صندوق الوارد (والـ spam).',
    'reset_password_instruction': 'تعيين كلمة المرور الجديدة.',
    'validate': 'تحقق',
    'search': 'بحث',
    'popularProducts': 'المنتجات الشائعة',
    'addToCart': 'أضف إلى السلة',
    'checkout': 'إتمام الطلب',
    'total': 'المجموع',
    'confirmOrder': 'تأكيد الطلب',
    'orderHistory': 'سجل الطلبات',
    'trackOrder': 'تتبع الطلب',
    'uploadImage': 'رفع صورة',
    'productName': 'اسم المنتج',
    'quantity': 'الكمية',
    'description': 'الوصف',
    'send': 'إرسال',
    'message': 'رسالة',
    'cart_empty': 'سلتك فارغة',
    'notification_default_title': 'إشعار',
    'open': 'فتح',
    'push_title_order_status': 'تحديث الطلب',
    'push_title_cart_abandoned': 'تذكير بالسلة',
    'push_title_promotion': 'عرض',
    'push_body_order_status': 'الطلب{orderLabel}: {status}',
    'push_order_status_default_status': 'محدّث',
    'push_body_cart_abandoned_with_count': 'لديك {count} عنصر(ات) في سلتك.',
    'push_body_cart_abandoned': 'لديك عناصر في سلتك.',
    'push_body_promotion': 'اكتشف عروضنا.',
    'order_status_pending': 'قيد الانتظار',
    'order_status_confirmed': 'مؤكد',
    'order_status_shipped': 'تم الشحن',
    'order_status_delivered': 'تم التوصيل',
    'order_status_cancelled': 'ملغى',
    'order_status_refunded': 'مسترد',
    'menu': 'القائمة',
    'favorites': 'المفضلة',
    'promotions': 'العروض',
    'chat': 'الدردشة',
    'logout': 'تسجيل الخروج',
    'refresh': 'تحديث',
    'retry': 'إعادة المحاولة',
    'clear_filter': 'مسح الفلتر',
    'discover': 'اكتشف',
    'discover_products': 'اكتشف منتجاتنا',
    'continue_shopping': 'متابعة التسوق',
    'products': 'المنتجات',
    'my_orders_title': 'طلباتي',
    'orders_total_count': '{count} طلب(ات) إجمالاً',
    'no_orders': 'لا توجد طلبات',
    'no_orders_hint': 'ستظهر طلباتك هنا',
    'order_details_title': 'تفاصيل الطلب',
    'order_information': 'معلومات',
    'name': 'الاسم',
    'phone': 'الهاتف',
    'country': 'البلد',
    'city': 'المدينة',
    'district': 'الحي',
    'address': 'العنوان',
    'number': 'الرقم',
    'date': 'التاريخ',
    'payment': 'الدفع',
    'customer': 'العميل',
    'shipping_address_title': 'عنوان التوصيل',
    'items': 'العناصر',
    'no_items': 'لا عناصر',
    'subtotal': 'المجموع الفرعي',
    'not_available': 'غير متاح',
    'unknown': 'غير معروف',
    'order_status_processing': 'قيد المعالجة',
    'added_to_favorites': '{name} أضيف إلى المفضلة',
    'leave_review': 'ترك مراجعة',
    'edit_my_review': 'تعديل مراجعتي',
    'edit': 'تعديل',
    'review_comment_optional': 'تعليق (اختياري)',
    'review_submitted_bonus': 'تم إرسال المراجعة. +5 نقاط مضافة',
    'review_error_with_details': 'خطأ في المراجعة: {error}',
    'product_not_found': 'المنتج غير موجود',
    'view_cart': 'عرض السلة',
    'in_stock_with_count': 'متوفر ({count})',
    'no_description_available': 'لا وصف متاح',
    'reviews': 'المراجعات',
    'no_reviews_yet': 'لا مراجعات بعد',
    'similar_products': 'منتجات مشابهة',
    'items_count': '{count} عنصر(ات)',
    'delivery': 'التوصيل',
    'out_of_stock': 'نفد من المخزون',
    'recommended_for_you': 'موصى به لك',
    'our_products': 'منتجاتنا',
    'search_products_hint': 'ماذا تبحث؟',
    'no_products_available': 'لا منتجات متاحة',
    'no_products_in_category': 'لا منتجات في هذه الفئة',
    'limited_offers_discounts': 'عروض وخصومات محدودة',
    'featured': 'مميز',
    'pull_to_refresh': 'اسحب للتحديث',
    'no_featured': 'لا عناصر مميزة حاليًا',
    'no_promotions': 'لا عروض حاليًا',
    'no_favorites': 'لا مفضلة',
    'favorites_empty_hint': 'أضف منتجاتك المفضلة هنا',
    'explore_products': 'استكشف المنتجات',
    'collections': 'المجموعات',
    'shared': 'مشارك',
    'sort_recent': 'الأحدث',
    'sort_name': 'الاسم',
    'sort_price_asc': 'السعر ↑',
    'sort_price_desc': 'السعر ↓',
    'messages': 'الرسائل',
    'support_assistance': 'الدعم والمساعدة',
    'search_conversation_hint': 'البحث في محادثة...',
    'no_conversation': 'لا محادثة',
    'start_new_conversation': 'بدء محادثة جديدة',
    'conversation_number': 'محادثة #{id}',
    'no_message': 'لا رسالة',
    'yesterday': 'أمس',
    'now': 'الآن',
    'day_short': 'ي',
    'hour_short': 'س',
    'minute_short': 'د',
    'filter': 'فلتر',
    'filter_categories': 'فلتر الفئات',
    'all': 'الكل',
    'popular': 'شائع',
    'new': 'جديد',
    'cancel': 'إلغاء',
    'authorize': 'تفويض',
    'notification_permission_rationale':
        'اسمح لـ GBA بإرسال إشعارات الطلبات والتوصيل والعروض. يمكنك تعطيلها من الإعدادات.',
    'apply': 'تطبيق',
    'press_back_again_to_exit': 'اضغط مرة أخرى للخروج',
    'no_results': 'لا نتائج',
    'try_another_keyword': 'جرب كلمة أخرى.',
    'search_category_hint': 'البحث في فئة...',
    'products_count': '{count} منتج(ات)',
    'explore': 'استكشف',
    'no_categories': 'لا فئات',
    'no_categories_hint': 'لا توجد فئات حاليًا.',
    'error_loading': 'خطأ تحميل',
    'cart_loading': 'جاري تحميل السلة…',
    'loading_categories': 'جاري تحميل الفئات…',
    'category': 'الفئة',
    'support_admin': 'دعم الأدمن',
    'my_account': 'حسابي',
    'navigation': 'التنقل',
    'special_orders': 'الطلبات الخاصة',
    'new_special_order': 'طلب خاص جديد',
    'my_special_orders': 'طلباتي الخاصة',
    'special_order_empty_title': 'لا طلبات خاصة حاليًا',
    'special_order_create_button': 'إنشاء طلب خاص',
    'special_order_generic_title': 'طلب خاص',
    'special_order_loading_error_with_details': 'خطأ تحميل: {error}',
    'special_order_shipping_air': 'جوي',
    'special_order_shipping_standard': 'قياسي',
    'special_order_quantity_delivery': 'الكمية: {qty}  •  التوصيل: {shipping}',
    'special_order_quote_with_amount': 'عرض السعر: {amount}',
    'special_order_quote_pending': 'في انتظار عرض السعر',
    'special_order_eta_with_range': 'الوصول المتوقع: {range}',
    'special_order_quote_status_with_status': 'حالة العرض: {status}',
    'special_order_details_title': 'تفاصيل الطلب الخاص',
    'special_order_not_found': 'الطلب الخاص غير موجود',
    'special_order_status_with_status': 'الحالة: {status}',
    'special_order_accept_quote': 'قبول',
    'special_order_reject_quote': 'رفض',
    'special_order_negotiate_quote': 'تفاوض (عرض مضاد)',
    'special_order_history': 'السجل',
    'special_order_timeline': 'الجدول الزمني',
    'special_order_offers_messages': 'العروض / الرسائل',
    'special_order_quote_accepted': 'تم قبول العرض',
    'special_order_quote_rejected': 'تم رفض العرض',
    'special_order_counter_offer_sent': 'تم إرسال العرض المضاد',
    'special_order_reject_dialog_title': 'رفض العرض',
    'special_order_counter_dialog_title': 'تقديم عرض مضاد',
    'special_order_unit_price_label': 'السعر للوحدة المقترح',
    'special_order_shipping_fee_label': 'رسوم التوصيل المقترحة',
    'special_order_optional_message_label': 'رسالة (اختياري)',
    'special_order_invalid_unit_price': 'سعر وحدة غير صالح',
    'special_order_quote': 'عرض السعر',
    'special_order_subtotal': 'المجموع الفرعي',
    'special_order_shipping': 'التوصيل',
    'special_order_tax': 'الضريبة',
    'special_order_service_fee': 'الخدمة',
    'special_order_total': 'المجموع',
    'special_order_valid_until_with_date': 'صالح حتى: {date}',
    'special_order_step_indicator': 'الخطوة {current}/{total}',
    'special_order_step_details': 'التفاصيل',
    'special_order_step_images': 'الصور',
    'special_order_step_delivery': 'التوصيل',
    'special_order_step_summary': 'الملخص',
    'save_and_continue': 'حفظ ومتابعة',
    'back': 'رجوع',
    'special_order_product_details_title': 'تفاصيل المنتج',
    'special_order_product_name_required': 'اسم المنتج مطلوب',
    'special_order_invalid_quantity': 'كمية غير صالحة',
    'special_order_description_required': 'الوصف مطلوب',
    'special_order_images_optional_title': 'صور (اختياري)',
    'special_order_add': 'إضافة',
    'special_order_images_hint': 'أضف صورًا لتحديد المنتج.',
    'special_order_delivery_title': 'التوصيل',
    'special_order_location_ready_with_accuracy': 'الموقع جاهز (±{meters}م)',
    'special_order_use_my_location': 'استخدم موقعي',
    'special_order_detecting_location': 'جاري تحديد موقعك...',
    'special_order_location_not_available': 'الموقع غير متاح',
    'special_order_shipping_method': 'طريقة التوصيل',
    'special_order_shipping_air_fast': 'جوي (أسرع)',
    'special_order_shipping_other_standard': 'أخرى (قياسي)',
    'special_order_notes_optional': 'ملاحظات (اختياري)',
    'special_order_notes_hint': 'تفاصيل، روابط، إلخ.',
    'special_order_summary_title': 'الملخص',
    'special_order_summary_product': 'المنتج',
    'special_order_summary_quantity': 'الكمية',
    'special_order_summary_delivery': 'التوصيل',
    'special_order_summary_images': 'الصور',
    'special_order_summary_notes': 'الملاحظات',
    'special_order_summary_description': 'الوصف',
    'special_order_gps_required_before_continue':
        'فعّل GPS وسجّل موقعك قبل المتابعة.',
    'special_order_gps_required_submit': 'مطلوب موقع GPS لإرسال هذا الطلب الخاص.',
    'no_internet_connection_title': 'لا يوجد اتصال بالإنترنت',
    'no_internet_connection_message': 'تحقق من الشبكة ثم أعد المحاولة.',
    'notification_body_audio_message': 'رسالة صوتية',
    'notification_body_image_message': 'صورة',
    'notification_body_new_message': 'رسالة جديدة',
    'special_order_gps_location': 'موقع GPS',
    'special_order_confirm_hint': 'بالموافقة، يُرسل طلبك للفريق للمعالجة.',
    'special_order_location_optional': 'الموقع غير متاح',
    'special_order_description': 'الوصف',
    'special_order_check_required_fields': 'يرجى التحقق من الحقول المطلوبة',
    'special_order_sent': 'تم إرسال الطلب الخاص',
    'special_order_send_error': 'خطأ في الإرسال',
    'special_order_draft_restored': 'تم استعادة المسودة',
    'special_order_geolocation_mobile_only': 'الموقع متاح على الجوال.',
    'special_order_enable_location_services': 'فعّل الموقع للمتابعة.',
    'special_order_location_permission_denied': 'تم رفض الإذن',
    'special_order_location_saved_with_accuracy': 'تم حفظ الموقع (±{meters}م)',
    'special_order_location_failed_with_details': 'تعذر الحصول على الموقع: {error}',
    'special_order_max_images': 'الحد الأقصى {count} صورة(ات)',
    'special_order_max_images_ignored': 'الحد الأقصى {count} صورة (تم تجاهل الباقي)',
    'special_order_image_too_large_with_size': 'الصورة كبيرة جدًا ({size} ميجا)',
    'special_order_pick_images_error_with_details': 'خطأ تحميل الصور: {error}',
    'special_order_status_pending': 'قيد الانتظار',
    'special_order_status_quoted': 'تم عرض السعر',
    'special_order_status_countered': 'عرض مضاد',
    'special_order_status_accepted': 'مقبول',
    'special_order_status_rejected': 'مرفوض',
    'no_events_yet': 'لا أحداث بعد',
    'personalization_gift': 'تخصيص / هدية',
    'coming_soon': '{label}: قريبًا',
    'favorites_not_found_title': 'المنتجات المفضلة غير موجودة',
    'favorites_not_found_hint': 'أعد تحميل قائمة المنتجات.',
    'product': 'المنتج',
    'removed_from_cart': '{name} أزيل من السلة',
    'removed_from_favorites': '{name} أزيل من المفضلة',
    'unnamed_product': 'منتج بدون اسم',
    'no_brand': 'بدون ماركة',
    'my_collections': 'مجموعاتي',
    'create_collection': 'إنشاء مجموعة',
    'collection_summer_2024': 'صيف 2024',
    'collection_essentials': 'أساسيات',
    'collection_gifts': 'هدايا',
    'store_name': 'GBA Store',
    'loading_products': 'جاري تحميل المنتجات…',
    'register_subtitle_join_store': 'انضم إلى GBA Store في 30 ثانية',
    'full_name': 'الاسم الكامل',
    'enter_your_name': 'يرجى إدخال اسمك',
    'enter_your_email': 'يرجى إدخال بريدك',
    'invalid_email': 'بريد غير صالح',
    'enter_your_password': 'يرجى إدخال كلمة المرور',
    'confirm_your_password': 'يرجى تأكيد كلمة المرور',
    'password_min_length_register': 'كلمة المرور 6 أحرف على الأقل.',
    'see_all': 'عرض الكل',
    'error_loading_with_details': 'خطأ تحميل: {error}',
    'added_to_cart': '{name} أضيف إلى السلة',
    'page_not_found_title': 'الصفحة غير موجودة',
    'no_route_for': 'لا مسار لـ: {route}',
    'back_to_home': 'العودة للرئيسية',
    'ad_mega_sale_title': '🎫 تخفيضات ضخمة -50%',
    'ad_mega_sale_subtitle': 'على كل الهواتف',
    'ad_free_delivery_title': '🚚 توصيل مجاني',
    'ad_free_delivery_subtitle': 'لأي طلب فوق 100€',
    'ad_flash_deal_title': '⚡ عرض فلاش',
    'ad_flash_deal_subtitle': 'عروض جديدة كل يوم',
    'ad_promo_code_title': '🎁 كود خصم: SAVE20',
    'ad_promo_code_subtitle': 'خصم 20% فوري',
    'notifications': 'الإشعارات',
    'appearance': 'المظهر',
    'privacy': 'الخصوصية',
    'danger_zone': 'منطقة خطرة',
    'push_notifications': 'إشعارات الدفع',
    'receive_notifications': 'استقبال الإشعارات',
    'notification_preferences': 'تفضيلات الإشعارات',
    'choose_categories': 'اختر الفئات',
    'sounds': 'الأصوات',
    'enable_sound_effects': 'تفعيل المؤثرات الصوتية',
    'vibrations': 'الاهتزاز',
    'haptic_feedback': 'اللمس الاهتزازي',
    'dark_mode': 'الوضع الداكن',
    'enable_dark_theme': 'تفعيل الوضع الداكن',
    'app_language': 'لغة التطبيق',
    'language_french': 'الفرنسية',
    'language_english': 'الإنجليزية',
    'language_arabic': 'العربية',
    'change_password': 'تغيير كلمة المرور',
    'change_password_subtitle': 'تحديث كلمة المرور',
    'privacy_policy': 'سياسة الخصوصية',
    'privacy_policy_subtitle': 'كيف نحمي بياناتك',
    'terms_of_service': 'شروط الاستخدام',
    'terms_of_service_subtitle': 'قراءة الشروط',
    'clear_cache': 'مسح الذاكرة المؤقتة',
    'cache_cleared_success': 'تم مسح الذاكرة المؤقتة',
    'logout_confirm_message': 'هل تريد تسجيل الخروج؟',
    'enable_disable_all_notifications': 'تفعيل/تعطيل كل الإشعارات',
    'notification_category_orders_subtitle': 'حالة الطلب، التوصيل، الإلغاء',
    'notification_category_promotions_subtitle': 'العروض، الخصومات، الوافدون الجدد',
    'notification_category_messages_subtitle': 'رسائل الدعم/الدردشة',
    'save': 'حفظ',
    'change_password_security_hint': 'لأمانك، أكد كلمة المرور الحالية.',
    'current_password': 'كلمة المرور الحالية',
    'new_password': 'كلمة المرور الجديدة',
    'confirm_password': 'تأكيد كلمة المرور',
    'error_user_email_not_found': 'تعذر المتابعة: البريد غير موجود.',
    'password_min_length': 'كلمة المرور الجديدة 6 أحرف على الأقل.',
    'passwords_do_not_match': 'كلمات المرور غير متطابقة.',
    'password_changed_success': 'تم تغيير كلمة المرور.',
    'error_with_details': 'خطأ: {error}',
    'share_unavailable_with_details': 'تعذر المشاركة: {error}',
    'link_copied': 'تم نسخ الرابط',
    'image_saved_to_gallery': 'تم حفظ الصورة في المعرض',
    'open_link_unavailable': 'تعذر فتح الرابط',
    'image': 'صورة',
    'download': 'تحميل',
    'share': 'مشاركة',
    'view_fullscreen': 'عرض بملء الشاشة',
    'copy_link': 'نسخ الرابط',
    'chat_error_sending_with_details': 'خطأ إرسال: {error}',
    'chat_error_sending_image_with_details': 'خطأ إرسال صورة: {error}',
    'image_upload_failed': 'فشل رفع الصورة',
    'support_client': 'دعم العملاء',
    'order_number': 'طلب #{id}',
    'order_number_label': 'رقم الطلب',
    'track_order': 'تتبع الطلب',
    'order_tracking_title': 'حالة الطلب',
    'search_product_hint': 'ماذا تبحث؟',
    'search_history': 'عمليات البحث الأخيرة',
    'search_clear_history': 'مسح',
    'price': 'السعر',
    'reset': 'إعادة تعيين',
    'filter_min_rating': 'الحد الأدنى للتقييم',
    'order_cancelled': 'الطلب ملغى',
    'current': 'الحالي',
    'permission_denied': 'تم رفض الإذن',
    'start_conversation': 'بدء المحادثة',
    'we_are_here_to_help': 'نحن هنا لمساعدتك',
    'type_your_message': 'اكتب رسالتك...',
    'conversation_info_title': 'معلومات المحادثة',
    'label_id': 'المعرف',
    'label_status': 'الحالة',
    'label_priority': 'الأولوية',
    'label_order': 'الطلب',
    'label_created_at': 'تاريخ الإنشاء',
    'today': 'اليوم',
    'conversation_status_active': 'نشط',
    'conversation_status_resolved': 'تم الحل',
    'conversation_status_archived': 'مؤرشف',
    'conversation_status_pending': 'قيد الانتظار',
    'access_blocked': 'الوصول مغلق',
    'account_suspended': 'الحساب موقوف',
    'suspension_reason': 'سبب الإيقاف',
    'what_to_do_now': 'ماذا تفعل الآن؟',
    'greeting_morning': 'صباح الخير',
    'greeting_afternoon': 'مساء الخير',
    'greeting_evening': 'مساء الخير',
    'auth_label_email': 'البريد الإلكتروني',
    'auth_label_password': 'كلمة المرور',
    'auth_label_full_name': 'الاسم الكامل',
    'auth_label_confirm_password': 'تأكيد كلمة المرور',
    'auth_forgot_password_link': 'نسيت كلمة المرور؟',
    'auth_login_button': 'تسجيل الدخول',
    'auth_no_account_yet': 'لا حساب بعد؟ ',
    'auth_sign_up_link': 'إنشاء حساب',
    'auth_already_have_account': 'لديك حساب بالفعل؟ ',
    'auth_enter_email': 'أدخل بريدك الإلكتروني',
    'auth_invalid_email_format': 'صيغة البريد غير صالحة',
    'auth_enter_password': 'أدخل كلمة المرور',
    'auth_min_6_chars': '6 أحرف على الأقل',
    'auth_enter_full_name': 'أدخل اسمك الكامل',
    'auth_enter_a_password': 'أدخل كلمة مرور',
    'auth_min_8_chars': '8 أحرف على الأقل',
    'auth_confirm_your_password': 'أكد كلمة المرور',
    'auth_at_least_1_upper': 'حرف كبير واحد على الأقل',
    'auth_at_least_1_digit': 'رقم واحد على الأقل',
    'auth_at_least_1_special': 'رمز خاص واحد على الأقل',
    'auth_resend_confirmation': 'إعادة إرسال بريد التأكيد ←',
    'auth_resend_confirmation_sent': 'تم إعادة إرسال بريد التأكيد.',
    'auth_error_invalid_credentials': 'تم رفض الدخول. تحقق من كلمة المرور أو فعّل بريدك (تحقق من صندوق الوارد).',
    'auth_error_server_db': 'خطأ في الخادم أثناء إنشاء الحساب. أعد المحاولة. إن استمر، تواصل مع الدعم.',
    'auth_error_email_exists': 'هذا البريد مسجّل مسبقًا. سجّل الدخول أو استخدم «نسيت كلمة المرور».',
    'auth_error_email_invalid': 'بريد غير صالح. أعد إدخال البريد (بدون مسافات أو رموز خفية) وأعد المحاولة.',
    'auth_error_generic': 'حدث خطأ. أعد المحاولة.',
    'auth_check_your_email': 'تحقق من بريدك',
    'auth_confirmation_sent_to': 'تم إرسال رابط التأكيد إلى\n{email}',
    'auth_resend_email_button': 'إعادة إرسال البريد',
    'auth_go_to_login': 'الذهاب لتسجيل الدخول',
    'auth_forgot_password_instruction_short': 'أدخل بريدك لاستلام رابط إعادة التعيين',
    'auth_send_link': 'إرسال الرابط',
    'auth_email_sent': 'تم إرسال البريد!',
    'auth_reset_link_sent_to': 'تم إرسال رابط إعادة التعيين إلى\n{email}',
    'auth_check_spam': 'تحقق من مجلد البريد العشوائي.',
    'auth_back_to_login': 'العودة لتسجيل الدخول',
    'auth_strength_very_weak': 'ضعيف جدًا',
    'auth_strength_weak': 'ضعيف',
    'auth_strength_medium': 'متوسط',
    'auth_strength_strong': 'قوي',
    'auth_criterion_chars': '≥ 8 أحرف',
    'auth_criterion_upper': 'حرف كبير',
    'auth_criterion_digit': 'رقم',
    'auth_criterion_special': 'رمز خاص',
    'auth_verify_email_title': 'تحقق من بريدك',
    'auth_reset_link_sent': 'تم إرسال رابط إعادة التعيين إلى\n{email}',
    'remember_me': 'تذكرني',
    'login_required_title': 'تسجيل الدخول مطلوب',
    'login_required_message': 'سجّل الدخول أو أنشئ حسابًا للوصول إلى هذه الميزة.',
    'login_required': 'تسجيل الدخول مطلوب',
    'browse_without_account': 'تصفح بدون حساب',
    'no_internet_connection': 'لا يوجد اتصال بالإنترنت',
    'check_connection_and_retry': 'تحقق من اتصالك وحاول مرة أخرى',
    'connection_error': 'خطأ في الاتصال. تحقق من اتصالك بالإنترنت.',
    'create_order': 'إنشاء طلب',
    'cash_on_delivery': 'الدفع عند التسليم',
    'location_services_disabled': 'خدمات الموقع معطلة',
    'enable_location_to_continue': 'قم بتفعيل خدمات الموقع للمتابعة',
    'open_settings': 'فتح الإعدادات',
    'location_permission_denied': 'تم رفض إذن الموقع',
    'location_permission_required': 'إذن الموقع مطلوب لهذه الميزة',
    'location_permission_permanently_denied': 'تم رفض إذن الموقع بشكل دائم. يرجى تفعيله في الإعدادات.',
    'welcome': 'مرحبا',
    'skip': 'تخطي',
    'percent_completed': '{percent}% مكتمل',
    'finish': 'إنهاء',
    'next': 'التالي',
    'complete_profile': 'أكمل ملفك الشخصي',
    'profile_info_speeds_checkout': 'تسرع هذه المعلومات عملية الدفع والتسليم.',
    'choose_app_language': 'اختر لغة التطبيق.',
    'choose_what_to_receive': 'اختر ما تريد استلامه.',
    'enable_notifications': 'تفعيل الإشعارات',
    'orders_notifications': 'الطلبات',
    'promotions_notifications': 'العروض',
    'messages_notifications': 'الرسائل',
  };

    String translate(String key) {
    switch (locale.languageCode) {
      case 'en':
        if (!_englishTranslations.containsKey(key)) {
          I18nAudit.instance.reportMissingKey(key: key, locale: locale);
        }
        return _englishTranslations[key] ?? key;
      case 'fr':
        if (!_frenchTranslations.containsKey(key)) {
          I18nAudit.instance.reportMissingKey(key: key, locale: locale);
        }
        return _frenchTranslations[key] ?? _englishTranslations[key] ?? key;
      case 'ar':
        if (!_arabicTranslations.containsKey(key)) {
          I18nAudit.instance.reportMissingKey(key: key, locale: locale);
        }
        return _arabicTranslations[key] ?? _englishTranslations[key] ?? _frenchTranslations[key] ?? key;
      default:
        if (!_englishTranslations.containsKey(key)) {
          I18nAudit.instance.reportMissingKey(key: key, locale: locale);
        }
        return _englishTranslations[key] ?? key;
    }
  }

  String translateParams(String key, Map<String, String> params) {
    var value = translate(key);
    for (final entry in params.entries) {
      value = value.replaceAll('{${entry.key}}', entry.value);
    }
    return value;
  }

  // ── Convenient getters for blocked screen translations ──
  String get access_blocked => translate('access_blocked');
  String get account_suspended => translate('account_suspended');
  String get suspension_reason => translate('suspension_reason');
  String get what_to_do_now => translate('what_to_do_now');
  String get contact_support_error => translate('contact_support_error');
  String get logout => translate('logout');
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'fr', 'ar'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
