import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';

import '../utils/i18n_audit.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  // Translations for English
  Map<String, String> _englishTranslations = {
    'appName': 'E-commerce Client',
    'home': 'Home',
    'categories': 'Categories',
    'cart': 'Cart',
    'orders': 'Orders',
    'profile': 'Profile',
    'specialOrder': 'Special Order',
    'messaging': 'Messaging',
    'settings': 'Settings',
    'language': 'Language',
    'helpSupport': 'Help & Support',
    'login': 'Login',
    'register': 'Register',
    'create_account': 'Create an account',
    'register_subtitle_join_store': 'Join GBA Store in 30 seconds',
    'full_name': 'Full name',
    'enter_your_name': 'Please enter your name',
    'enter_your_email': 'Please enter your email',
    'invalid_email': 'Invalid email',
    'enter_your_password': 'Please enter your password',
    'confirm_your_password': 'Please confirm your password',
    'accept_legal_prefix': 'I accept the ',
    'accept_legal_and': ' and the ',
    'already_have_account': 'Already have an account?',
    'register_accept_legal_required': 'Please accept the Terms of Service and Privacy Policy.',
    'register_account_created_check_email': 'Account created. Check your email then log in.',
    'admin_support_available': 'Customer service available',
    'user_not_logged_in': 'User not logged in',
    'email': 'Email',
    'password': 'Password',
    'forgotPassword': 'Forgot Password?',
    'search': 'Search',
    'popularProducts': 'Popular Products',
    'addToCart': 'Add to Cart',
    'checkout': 'Checkout',
    'total': 'Total',
    'confirmOrder': 'Confirm Order',
    'orderHistory': 'Order History',
    'trackOrder': 'Track Order',
    'uploadImage': 'Upload Image',
    'productName': 'Product Name',
    'quantity': 'Quantity',
    'description': 'Description',
    'send': 'Send',
    'message': 'Message',
    'cart_empty': 'Your cart is empty',
    'notification_default_title': 'Notification',
    'open': 'Open',
    'push_title_order_status': 'Order update',
    'push_title_cart_abandoned': 'Cart reminder',
    'push_title_promotion': 'Promotion',
    'push_body_order_status': 'Order{orderLabel}: {status}',
    'push_order_status_default_status': 'updated',
    'push_body_cart_abandoned_with_count': 'You have {count} item(s) in your cart.',
    'push_body_cart_abandoned': 'You have items in your cart.',
    'push_body_promotion': 'Discover our offers.',
    'order_status_pending': 'Pending',
    'order_status_confirmed': 'Confirmed',
    'order_status_shipped': 'Shipped',
    'order_status_delivered': 'Delivered',
    'order_status_cancelled': 'Cancelled',
    'order_status_refunded': 'Refunded',
    'menu': 'Menu',
    'favorites': 'Favorites',
    'promotions': 'Promotions',
    'chat': 'Chat',
    'logout': 'Logout',
    'refresh': 'Refresh',
    'retry': 'Retry',
    'clear_filter': 'Clear filter',
    'discover': 'Discover',
    'discover_products': 'Discover our products',
    'continue_shopping': 'Continue shopping',
    'items_count': '{count} item(s)',
    'delivery': 'Delivery',
    'out_of_stock': 'Out of stock',
    'recommended_for_you': 'Recommended for you',
    'our_products': 'Our Products',
    'search_products_hint': '🔍 What are you looking for?',
    'no_products_available': 'No products available',
    'no_products_in_category': 'No products in this category',
    'limited_offers_discounts': 'Limited-time offers and discounts',
    'featured': 'Featured',
    'pull_to_refresh': 'Pull down to refresh',
    'no_featured': 'No featured items for now',
    'no_promotions': 'No promotions at the moment',
    'no_favorites': 'No favorites',
    'favorites_empty_hint': 'Add your favorite products here',
    'explore_products': 'Explore products',
    'collections': 'Collections',
    'shared': 'Shared',
    'sort_recent': 'Recent',
    'sort_name': 'Name',
    'sort_price_asc': 'Price ↑',
    'sort_price_desc': 'Price ↓',
    'messages': 'Messages',
    'support_assistance': 'Support & Assistance',
    'search_conversation_hint': 'Search a conversation...',
    'no_conversation': 'No conversation',
    'start_new_conversation': 'Start a new conversation',
    'conversation_number': 'Conversation #{id}',
    'no_message': 'No message',
    'yesterday': 'Yesterday',
    'now': 'Now',
    'day_short': 'd',
    'hour_short': 'h',
    'minute_short': 'm',
    'filter': 'Filter',
    'filter_categories': 'Filter categories',
    'all': 'All',
    'popular': 'Popular',
    'new': 'New',
    'cancel': 'Cancel',
    'apply': 'Apply',
    'no_results': 'No results',
    'try_another_keyword': 'Try another keyword.',
    'search_category_hint': 'Search a category...',
    'products_count': '{count} product(s)',
    'no_categories': 'No categories',
    'no_categories_hint': "You don't have any categories at the moment.",
    'error_loading': 'Loading error',
    'cart_loading': 'Loading cart…',
    'loading_categories': 'Loading categories…',
    'category': 'Category',
    'support_admin': 'Admin Support',
    'my_account': 'My account',
    'navigation': 'Navigation',
    'special_orders': 'Special orders',
    'new_special_order': 'New special order',
    'my_special_orders': 'My special orders',
    'personalization_gift': 'Personalization / Gift',
    'coming_soon': '{label}: coming soon',
    'favorites_not_found_title': 'Favorite products not found',
    'favorites_not_found_hint': 'Reload the product list.',
    'product': 'Product',
    'removed_from_cart': '{name} removed from cart',
    'removed_from_favorites': '{name} removed from favorites',
    'unnamed_product': 'Unnamed product',
    'no_brand': 'No brand',
    'my_collections': 'My Collections',
    'create_collection': 'Create a collection',
    'collection_summer_2024': 'Summer 2024',
    'collection_essentials': 'Essentials',
    'collection_gifts': 'Gifts',
    'store_name': 'GBA Store',
    'loading_products': 'Loading products…',
    'welcome_to_store': 'Welcome to {store}',
    'see_all': 'See all',
    'error_loading_with_details': 'Loading error: {error}',
    'added_to_cart': '{name} added to cart',
    'page_not_found_title': 'Page not found',
    'no_route_for': 'No route for: {route}',
    'back_to_home': 'Back to home',
    'ad_mega_sale_title': '🎯 MEGA SALE -50%',
    'ad_mega_sale_subtitle': 'On all smartphones',
    'ad_free_delivery_title': '🚚 Free Delivery',
    'ad_free_delivery_subtitle': 'For any order over 100€',
    'ad_flash_deal_title': '⚡ Flash Deal',
    'ad_flash_deal_subtitle': 'New offers every day',
    'ad_promo_code_title': '🎁 Promo code: SAVE20',
    'ad_promo_code_subtitle': '20% instant discount',
    'notifications': 'Notifications',
    'appearance': 'Appearance',
    'privacy': 'Privacy',
    'danger_zone': 'Danger zone',
    'push_notifications': 'Push notifications',
    'receive_notifications': 'Receive notifications',
    'notification_preferences': 'Notification preferences',
    'choose_categories': 'Choose categories',
    'sounds': 'Sounds',
    'enable_sound_effects': 'Enable sound effects',
    'vibrations': 'Vibrations',
    'haptic_feedback': 'Haptic feedback',
    'dark_mode': 'Dark mode',
    'enable_dark_theme': 'Enable dark theme',
    'app_language': 'App language',
    'change_password': 'Change password',
    'change_password_subtitle': 'Update your password',
    'privacy_policy': 'Privacy policy',
    'privacy_policy_subtitle': 'How we protect your data',
    'terms_of_service': 'Terms of service',
    'terms_of_service_subtitle': 'Read the terms',
    'clear_cache': 'Clear cache',
    'cache_cleared_success': 'Cache cleared successfully',
    'logout_confirm_message': 'Do you really want to log out?',
    'enable_disable_all_notifications': 'Enable/Disable all notifications',
    'notification_category_orders_subtitle': 'Order status, delivery, cancellation',
    'notification_category_promotions_subtitle': 'Offers, discounts, new arrivals',
    'notification_category_messages_subtitle': 'New support/chat messages',
    'save': 'Save',
    'change_password_security_hint': 'For your security, confirm your current password.',
    'current_password': 'Current password',
    'new_password': 'New password',
    'confirm_password': 'Confirm password',
    'error_user_email_not_found': 'Unable to continue: user email not found.',
    'password_min_length': 'The new password must be at least 6 characters.',
    'passwords_do_not_match': 'Passwords do not match.',
    'password_changed_success': 'Password changed.',
    'error_with_details': 'Error: {error}',
    'share_unavailable_with_details': 'Unable to share: {error}',
    'link_copied': 'Link copied',
    'copy_unavailable_with_details': 'Unable to copy: {error}',
    'open_link_unavailable': 'Unable to open the link',
    'image': 'Image',
    'download': 'Download',
    'share': 'Share',
    'view_fullscreen': 'View full screen',
    'copy_link': 'Copy link',
    'chat_error_sending_with_details': 'Send error: {error}',
    'chat_error_sending_image_with_details': 'Image send error: {error}',
    'image_upload_failed': 'Image upload failed',
    'support_client': 'Customer Support',
    'order_number': 'Order #{id}',
    'start_conversation': 'Start the conversation',
    'we_are_here_to_help': 'We are here to help you',
    'type_your_message': 'Type your message...',
    'conversation_info_title': 'Conversation information',
    'label_id': 'ID',
    'label_status': 'Status',
    'label_priority': 'Priority',
    'label_order': 'Order',
    'label_created_at': 'Created at',
    'today': 'Today',
    'conversation_status_active': 'Active',
    'conversation_status_resolved': 'Resolved',
    'conversation_status_archived': 'Archived',
    'conversation_status_pending': 'Pending',
    'conversation_priority_urgent': 'Urgent',
    'conversation_priority_high': 'High',
    'conversation_priority_normal': 'Normal',
    'conversation_priority_low': 'Low',
    'privacy_policy_section1_title': '1. Collected data',
    'privacy_policy_section1_body':
        'We collect the information needed to create your account, process your orders and improve the experience (e.g. email, name, phone number, addresses).',
    'privacy_policy_section2_title': '2. Use of data',
    'privacy_policy_section2_body':
        'Data is used for: authentication, delivery, customer support, analytics, fraud prevention.',
    'privacy_policy_section2_body_location':
        'If you use the geolocation feature for delivery, we may process your location only to facilitate delivery. Location is requested only after an explicit action (e.g. button "Use my location") when placing an order or a special order, and is not collected in the background.',
    'privacy_policy_section3_title': '3. Notifications',
    'privacy_policy_section3_body':
        'If you enable notifications, the app may use a notification identifier (token) to send you messages (order status, promotions).',
    'privacy_policy_section4_title': '4. Sharing',
    'privacy_policy_section4_body':
        'We do not sell your data. Some technical services (e.g. authentication, database) may process data to provide the service.',
    'privacy_policy_section5_title': '5. Your rights',
    'privacy_policy_section5_body':
        'You can request access, correction or deletion of your data according to applicable regulations.',
    'terms_of_service_section1_title': '1. Purpose',
    'terms_of_service_section1_body':
        'These terms define the rules for using the application and related services.',
    'terms_of_service_section2_title': '2. User account',
    'terms_of_service_section2_body':
        'You are responsible for keeping your credentials confidential and for the use of your account.',
    'terms_of_service_section3_title': '3. Orders and payment',
    'terms_of_service_section3_body':
        'Orders are subject to availability. Prices and fees may change. Payment may be processed by a provider.',
    'terms_of_service_section4_title': '4. Delivery',
    'terms_of_service_section4_body':
        'Delivery times are indicative. Make sure to provide a correct address.',
    'terms_of_service_section4_body_location':
        'If you choose to use the geolocation feature, your location may be used only to facilitate delivery. Location is requested only after an explicit action (e.g. button "Use my location") when placing an order or a special order, and is not collected in the background.',
    'terms_of_service_section5_title': '5. Support',
    'terms_of_service_section5_body':
        'For any questions, contact support through the available channels in the application.',
  };

  // Translations for French
  Map<String, String> _frenchTranslations = {
    'appName': 'GBA',
    'home': 'Accueil',
    'categories': 'Catégories',
    'cart': 'Panier',
    'orders': 'Commandes',
    'profile': 'Profil',
    'specialOrder': 'Commande Spéciale',
    'messaging': 'Messagerie',
    'settings': 'Paramètres',
    'language': 'Langue',
    'helpSupport': 'Aide et Support',
    'login': 'Connexion',
    'register': 'Inscription',
    'create_account': 'Créer un compte',
    'register_subtitle_join_store': 'Rejoignez GBA Store en 30 secondes',
    'full_name': 'Nom complet',
    'enter_your_name': 'Veuillez entrer votre nom',
    'enter_your_email': 'Veuillez entrer votre email',
    'invalid_email': 'Email invalide',
    'enter_your_password': 'Veuillez entrer votre mot de passe',
    'confirm_your_password': 'Veuillez confirmer votre mot de passe',
    'accept_legal_prefix': 'J\'accepte les ',
    'accept_legal_and': ' et la ',
    'already_have_account': 'Déjà un compte ?',
    'register_accept_legal_required': 'Veuillez accepter les CGU et la Politique de confidentialité.',
    'register_account_created_check_email': 'Compte créé. Vérifiez votre email puis connectez-vous.',
    'admin_support_available': 'Service client disponible',
    'user_not_logged_in': 'Utilisateur non connecté',
    'email': 'Email',
    'password': 'Mot de passe',
    'forgotPassword': 'Mot de passe oublié?',
    'search': 'Recherche',
    'popularProducts': 'Produits Populaires',
    'addToCart': 'Ajouter au Panier',
    'checkout': 'Validation',
    'total': 'Total',
    'confirmOrder': 'Confirmer la Commande',
    'orderHistory': 'Historique des Commandes',
    'trackOrder': 'Suivre la Commande',
    'uploadImage': 'Télécharger une Image',
    'productName': 'Nom du Produit',
    'quantity': 'Quantité',
    'description': 'Description',
    'send': 'Envoyer',
    'message': 'Message',
    'cart_empty': 'Votre panier est vide',
    'notification_default_title': 'Notification',
    'open': 'Ouvrir',
    'push_title_order_status': 'Mise à jour commande',
    'push_title_cart_abandoned': 'Panier en attente',
    'push_title_promotion': 'Promotion',
    'push_body_order_status': 'Commande{orderLabel}: {status}',
    'push_order_status_default_status': 'mise à jour',
    'push_body_cart_abandoned_with_count': 'Tu as {count} article(s) dans ton panier.',
    'push_body_cart_abandoned': 'Tu as des articles dans ton panier.',
    'push_body_promotion': 'Découvre nos offres.',
    'order_status_pending': 'En attente',
    'order_status_confirmed': 'Confirmée',
    'order_status_shipped': 'Expédiée',
    'order_status_delivered': 'Livrée',
    'order_status_cancelled': 'Annulée',
    'order_status_refunded': 'Remboursée',
    'menu': 'Menu',
    'favorites': 'Favoris',
    'promotions': 'Promotions',
    'chat': 'Chat',
    'logout': 'Déconnexion',
    'refresh': 'Rafraîchir',
    'retry': 'Réessayer',
    'clear_filter': 'Effacer filtre',
    'discover': 'Découvrir',
    'discover_products': 'Découvrez nos produits',
    'continue_shopping': 'Continuer vos achats',
    'items_count': '{count} article(s)',
    'delivery': 'Livraison',
    'out_of_stock': 'Rupture de stock',
    'recommended_for_you': 'Recommandé pour vous',
    'our_products': 'Nos Produits',
    'search_products_hint': '🔍 Que recherchez-vous?',
    'no_products_available': 'Aucun produit disponible',
    'no_products_in_category': 'Aucun produit dans cette catégorie',
    'limited_offers_discounts': 'Offres limitées et réductions',
    'featured': 'Vedettes',
    'pull_to_refresh': 'Tire vers le bas pour rafraîchir',
    'no_featured': 'Aucune vedette pour le moment',
    'no_promotions': 'Aucune promotion en cours',
    'no_favorites': 'Aucun favori',
    'favorites_empty_hint': 'Ajoutez vos produits préférés ici',
    'explore_products': 'Explorer les produits',
    'collections': 'Collections',
    'shared': 'Partagés',
    'sort_recent': 'Récents',
    'sort_name': 'Nom',
    'sort_price_asc': 'Prix ↑',
    'sort_price_desc': 'Prix ↓',
    'messages': 'Messages',
    'support_assistance': 'Support & Assistance',
    'search_conversation_hint': 'Rechercher une conversation...',
    'no_conversation': 'Aucune conversation',
    'start_new_conversation': 'Commencez une nouvelle conversation',
    'conversation_number': 'Conversation #{id}',
    'no_message': 'Pas de message',
    'yesterday': 'Hier',
    'now': 'Maintenant',
    'day_short': 'j',
    'hour_short': 'h',
    'minute_short': 'm',
    'filter': 'Filtrer',
    'filter_categories': 'Filtrer les catégories',
    'all': 'Tout',
    'popular': 'Populaires',
    'new': 'Nouveautés',
    'cancel': 'Annuler',
    'apply': 'Appliquer',
    'no_results': 'Aucun résultat',
    'try_another_keyword': 'Essaie un autre mot-clé.',
    'search_category_hint': 'Rechercher une catégorie…',
    'products_count': '{count} produits',
    'no_categories': 'Aucune catégorie',
    'no_categories_hint': 'Vous n\'avez aucune catégorie pour le moment.',
    'error_loading': 'Erreur de chargement',
    'cart_loading': 'Chargement du panier…',
    'loading_categories': 'Chargement des catégories…',
    'category': 'Catégorie',
    'support_admin': 'Support Admin',
    'my_account': 'Mon compte',
    'navigation': 'Navigation',
    'special_orders': 'Commandes spéciales',
    'new_special_order': 'Nouvelle commande spéciale',
    'my_special_orders': 'Mes commandes spéciales',
    'personalization_gift': 'Personnalisation / Cadeau',
    'coming_soon': '{label} : bientôt disponible',
    'favorites_not_found_title': 'Produits favoris introuvables',
    'favorites_not_found_hint': 'Recharge la liste des produits.',
    'product': 'Produit',
    'removed_from_cart': '{name} retiré du panier',
    'removed_from_favorites': '{name} retiré des favoris',
    'unnamed_product': 'Produit sans nom',
    'no_brand': 'Sans marque',
    'my_collections': 'Mes Collections',
    'create_collection': 'Créer une collection',
    'collection_summer_2024': 'Été 2024',
    'collection_essentials': 'Essentiels',
    'collection_gifts': 'Cadeaux',
    'store_name': 'GBA Store',
    'loading_products': 'Chargement des produits…',
    'welcome_to_store': 'Bienvenue chez {store}',
    'see_all': 'Voir tout',
    'error_loading_with_details': 'Erreur de chargement: {error}',
    'added_to_cart': '{name} ajouté au panier',
    'page_not_found_title': 'Page introuvable',
    'no_route_for': 'Aucune route pour : {route}',
    'back_to_home': 'Retour à l\'accueil',
    'ad_mega_sale_title': '🎯 MEGA SOLDES -50%',
    'ad_mega_sale_subtitle': 'Sur tous les smartphones',
    'ad_free_delivery_title': '🚚 Livraison Gratuite',
    'ad_free_delivery_subtitle': 'Pour toute commande +100€',
    'ad_flash_deal_title': '⚡ Flash Deal',
    'ad_flash_deal_subtitle': 'Nouvelles offres chaque jour',
    'ad_promo_code_title': '🎁 Code Promo: SAVE20',
    'ad_promo_code_subtitle': '20% de réduction immédiate',
    'notifications': 'Notifications',
    'appearance': 'Apparence',
    'privacy': 'Confidentialité',
    'danger_zone': 'Zone de danger',
    'push_notifications': 'Notifications push',
    'receive_notifications': 'Recevoir des notifications',
    'notification_preferences': 'Préférences notifications',
    'choose_categories': 'Choisir les catégories',
    'sounds': 'Sons',
    'enable_sound_effects': 'Activer les effets sonores',
    'vibrations': 'Vibrations',
    'haptic_feedback': 'Retour haptique',
    'dark_mode': 'Mode sombre',
    'enable_dark_theme': 'Activer le thème sombre',
    'app_language': 'Langue de l\'application',
    'change_password': 'Changer mot de passe',
    'change_password_subtitle': 'Modifier votre mot de passe',
    'privacy_policy': 'Politique de confidentialité',
    'privacy_policy_subtitle': 'Comment nous protégeons vos données',
    'terms_of_service': "Conditions d'utilisation",
    'terms_of_service_subtitle': 'Lire les CGU',
    'clear_cache': 'Vider le cache',
    'cache_cleared_success': 'Cache vidé avec succès',
    'logout_confirm_message': 'Voulez-vous vraiment vous déconnecter?',
    'enable_disable_all_notifications': 'Activer/Désactiver toutes les notifications',
    'notification_category_orders_subtitle': 'Statut de commande, livraison, annulation',
    'notification_category_promotions_subtitle': 'Offres, réductions, nouveautés',
    'notification_category_messages_subtitle': 'Nouveaux messages support / chat',
    'save': 'Enregistrer',
    'change_password_security_hint': 'Pour ta sécurité, confirme ton mot de passe actuel.',
    'current_password': 'Mot de passe actuel',
    'new_password': 'Nouveau mot de passe',
    'confirm_password': 'Confirmer le mot de passe',
    'error_user_email_not_found': 'Impossible: email utilisateur introuvable.',
    'password_min_length': 'Le nouveau mot de passe doit contenir au moins 6 caractères.',
    'passwords_do_not_match': 'Les mots de passe ne correspondent pas.',
    'password_changed_success': 'Mot de passe modifié.',
    'error_with_details': 'Erreur: {error}',
    'share_unavailable_with_details': 'Impossible de partager: {error}',
    'link_copied': 'Lien copié',
    'copy_unavailable_with_details': 'Impossible de copier: {error}',
    'open_link_unavailable': "Impossible d'ouvrir le lien",
    'image': 'Image',
    'download': 'Télécharger',
    'share': 'Partager',
    'view_fullscreen': 'Voir en plein écran',
    'copy_link': 'Copier le lien',
    'chat_error_sending_with_details': 'Erreur envoi: {error}',
    'chat_error_sending_image_with_details': 'Erreur envoi image: {error}',
    'image_upload_failed': "Upload de l'image échoué",
    'support_client': 'Support Client',
    'order_number': 'Commande #{id}',
    'start_conversation': 'Commencez la conversation',
    'we_are_here_to_help': 'Nous sommes là pour vous aider',
    'type_your_message': 'Tapez votre message...',
    'conversation_info_title': 'Informations de la conversation',
    'label_id': 'ID',
    'label_status': 'Statut',
    'label_priority': 'Priorité',
    'label_order': 'Commande',
    'label_created_at': 'Créée le',
    'today': "Aujourd'hui",
    'conversation_status_active': 'Active',
    'conversation_status_resolved': 'Résolue',
    'conversation_status_archived': 'Archivée',
    'conversation_status_pending': 'En attente',
    'conversation_priority_urgent': 'Urgent',
    'conversation_priority_high': 'Élevée',
    'conversation_priority_normal': 'Normal',
    'conversation_priority_low': 'Faible',
    'privacy_policy_section1_title': '1. Données collectées',
    'privacy_policy_section1_body':
        "Nous collectons les informations nécessaires pour créer votre compte, traiter vos commandes et améliorer l'expérience (ex: email, nom, téléphone, adresses).",
    'privacy_policy_section2_title': '2. Utilisation des données',
    'privacy_policy_section2_body':
        'Les données sont utilisées pour: authentification, livraison, support client, statistiques, prévention de fraude.',
    'privacy_policy_section2_body_location':
        "Si vous utilisez la fonctionnalité de géolocalisation pour la livraison, nous pouvons traiter votre position uniquement pour faciliter la livraison. La localisation n'est demandée qu'après une action explicite (ex: bouton \"Utiliser ma position\") lors du passage d'une commande ou d'une commande spéciale, et n'est pas collectée en arrière-plan.",
    'privacy_policy_section3_title': '3. Notifications',
    'privacy_policy_section3_body':
        "Si vous activez les notifications, l'application peut utiliser un identifiant de notification (token) afin de vous envoyer des messages (statut commande, promotions).",
    'privacy_policy_section4_title': '4. Partage',
    'privacy_policy_section4_body':
        "Nous ne vendons pas vos données. Certains services techniques (ex: authentification, base de données) peuvent traiter des données pour fournir le service.",
    'privacy_policy_section5_title': '5. Vos droits',
    'privacy_policy_section5_body':
        "Vous pouvez demander l'accès, la correction ou la suppression de vos données selon la réglementation applicable.",
    'terms_of_service_section1_title': '1. Objet',
    'terms_of_service_section1_body':
        "Les présentes conditions définissent les règles d'utilisation de l'application et des services associés.",
    'terms_of_service_section2_title': '2. Compte utilisateur',
    'terms_of_service_section2_body':
        "Vous êtes responsable de la confidentialité de vos identifiants et de l'utilisation de votre compte.",
    'terms_of_service_section3_title': '3. Commandes et paiement',
    'terms_of_service_section3_body':
        'Les commandes sont soumises à disponibilité. Les prix et frais peuvent changer. Le paiement peut être traité par un prestataire.',
    'terms_of_service_section4_title': '4. Livraison',
    'terms_of_service_section4_body':
        'Les délais de livraison sont indicatifs. Assurez-vous de fournir une adresse correcte.',
    'terms_of_service_section4_body_location':
        "Si vous choisissez d'utiliser la fonctionnalité de géolocalisation, votre position peut être utilisée uniquement pour faciliter la livraison. La localisation n'est demandée qu'après une action explicite (ex: bouton \"Utiliser ma position\") lors du passage d'une commande ou d'une commande spéciale, et n'est pas collectée en arrière-plan.",
    'terms_of_service_section5_title': '5. Support',
    'terms_of_service_section5_body':
        "Pour toute question, contactez le support via les canaux disponibles dans l'application.",
  };

  // Translations for Arabic
  Map<String, String> _arabicTranslations = {
    'appName': 'عميل التجارة الإلكترونية',
    'home': 'الرئيسية',
    'categories': 'الفئات',
    'cart': 'السلة',
    'orders': 'الطلبات',
    'profile': 'الملف الشخصي',
    'specialOrder': 'طلب خاص',
    'messaging': 'المراسلة',
    'settings': 'الإعدادات',
    'language': 'اللغة',
    'helpSupport': 'المساعدة والدعم',
    'login': 'تسجيل الدخول',
    'register': 'تسجيل',
    'create_account': 'إنشاء حساب',
    'register_subtitle_join_store': 'انضم إلى متجر GBA في 30 ثانية',
    'full_name': 'الاسم الكامل',
    'enter_your_name': 'يرجى إدخال اسمك',
    'enter_your_email': 'يرجى إدخال بريدك الإلكتروني',
    'invalid_email': 'بريد إلكتروني غير صالح',
    'enter_your_password': 'يرجى إدخال كلمة المرور',
    'confirm_your_password': 'يرجى تأكيد كلمة المرور',
    'accept_legal_prefix': 'أوافق على ',
    'accept_legal_and': ' و',
    'already_have_account': 'لديك حساب بالفعل؟',
    'register_accept_legal_required': 'يرجى الموافقة على شروط الاستخدام وسياسة الخصوصية.',
    'register_account_created_check_email': 'تم إنشاء الحساب. تحقّق من بريدك الإلكتروني ثم سجّل الدخول.',
    'admin_support_available': 'خدمة العملاء متاحة',
    'user_not_logged_in': 'المستخدم غير مسجّل الدخول',
    'email': 'البريد الإلكتروني',
    'password': 'كلمة المرور',
    'forgotPassword': 'هل نسيت كلمة المرور؟',
    'cart_empty': 'سلة التسوق فارغة',
    'search': 'بحث',
    'popularProducts': 'المنتجات الشائعة',
    'addToCart': 'أضف إلى السلة',
    'checkout': 'التحقق من',
    'total': 'المجموع',
    'confirmOrder': 'تأكيد الطلب',
    'orderHistory': 'سجل الطلبات',
    'trackOrder': 'تتبع الطلب',
    'uploadImage': 'تحميل صورة',
    'productName': 'اسم المنتج',
    'quantity': 'الكمية',
    'description': 'الوصف',
    'send': 'إرسال',
    'message': 'رسالة',
    'notification_default_title': 'إشعار',
    'open': 'فتح',
    'push_title_order_status': 'تحديث الطلب',
    'push_title_cart_abandoned': 'تذكير بالسلة',
    'push_title_promotion': 'عرض ترويجي',
    'push_body_order_status': 'الطلب{orderLabel}: {status}',
    'push_order_status_default_status': 'تم تحديثه',
    'push_body_cart_abandoned_with_count': 'لديك {count} عنصرًا في سلتك.',
    'push_body_cart_abandoned': 'لديك عناصر في سلتك.',
    'push_body_promotion': 'اكتشف عروضنا.',
    'order_status_pending': 'قيد الانتظار',
    'order_status_confirmed': 'تم التأكيد',
    'order_status_shipped': 'تم الشحن',
    'order_status_delivered': 'تم التسليم',
    'order_status_cancelled': 'تم الإلغاء',
    'order_status_refunded': 'تم الاسترداد',
    'menu': 'القائمة',
    'favorites': 'المفضلة',
    'promotions': 'العروض',
    'chat': 'الدردشة',
    'logout': 'تسجيل الخروج',
    'refresh': 'تحديث',
    'retry': 'إعادة المحاولة',
    'clear_filter': 'مسح التصفية',
    'discover': 'اكتشف',
    'discover_products': 'اكتشف منتجاتنا',
    'continue_shopping': 'متابعة التسوق',
    'items_count': '{count} عنصر',
    'delivery': 'التوصيل',
    'out_of_stock': 'غير متوفر',
    'recommended_for_you': 'موصى به لك',
    'our_products': 'منتجاتنا',
    'search_products_hint': '🔍 ماذا تبحث عنه؟',
    'no_products_available': 'لا توجد منتجات متاحة',
    'no_products_in_category': 'لا توجد منتجات في هذه الفئة',
    'limited_offers_discounts': 'عروض وخصومات لفترة محدودة',
    'featured': 'مختارة',
    'pull_to_refresh': 'اسحب للأسفل للتحديث',
    'no_featured': 'لا توجد عناصر مختارة حالياً',
    'no_promotions': 'لا توجد عروض حالياً',
    'no_favorites': 'لا توجد مفضلات',
    'favorites_empty_hint': 'أضف منتجاتك المفضلة هنا',
    'explore_products': 'استكشاف المنتجات',
    'collections': 'المجموعات',
    'shared': 'المشتركة',
    'sort_recent': 'الأحدث',
    'sort_name': 'الاسم',
    'sort_price_asc': 'السعر ↑',
    'sort_price_desc': 'السعر ↓',
    'messages': 'الرسائل',
    'support_assistance': 'الدعم والمساعدة',
    'search_conversation_hint': 'ابحث عن محادثة...',
    'no_conversation': 'لا توجد محادثة',
    'start_new_conversation': 'ابدأ محادثة جديدة',
    'conversation_number': 'محادثة #{id}',
    'no_message': 'لا توجد رسالة',
    'yesterday': 'أمس',
    'now': 'الآن',
    'day_short': 'ي',
    'hour_short': 'س',
    'minute_short': 'د',
    'filter': 'تصفية',
    'filter_categories': 'تصفية الفئات',
    'all': 'الكل',
    'popular': 'الأكثر شيوعاً',
    'new': 'الجديد',
    'cancel': 'إلغاء',
    'apply': 'تطبيق',
    'no_results': 'لا توجد نتائج',
    'try_another_keyword': 'جرّب كلمة أخرى.',
    'search_category_hint': 'ابحث عن فئة…',
    'products_count': '{count} منتج',
    'no_categories': 'لا توجد فئات',
    'no_categories_hint': 'ليس لديك أي فئات في الوقت الحالي.',
    'error_loading': 'خطأ في التحميل',
    'cart_loading': 'جارٍ تحميل السلة…',
    'loading_categories': 'جارٍ تحميل الفئات…',
    'category': 'فئة',
    'support_admin': 'دعم المشرف',
    'my_account': 'حسابي',
    'navigation': 'التنقل',
    'special_orders': 'طلبات خاصة',
    'new_special_order': 'طلب خاص جديد',
    'my_special_orders': 'طلباتي الخاصة',
    'personalization_gift': 'تخصيص / هدية',
    'coming_soon': '{label}: قريباً',
    'favorites_not_found_title': 'تعذر العثور على المنتجات المفضلة',
    'favorites_not_found_hint': 'أعد تحميل قائمة المنتجات.',
    'product': 'منتج',
    'removed_from_cart': 'تمت إزالة {name} من السلة',
    'removed_from_favorites': 'تمت إزالة {name} من المفضلة',
    'unnamed_product': 'منتج بدون اسم',
    'no_brand': 'بدون علامة تجارية',
    'my_collections': 'مجموعاتي',
    'create_collection': 'إنشاء مجموعة',
    'collection_summer_2024': 'صيف 2024',
    'collection_essentials': 'الأساسيات',
    'collection_gifts': 'هدايا',
    'store_name': 'متجر GBA',
    'loading_products': 'جارٍ تحميل المنتجات…',
    'welcome_to_store': 'مرحبًا بك في {store}',
    'see_all': 'عرض الكل',
    'error_loading_with_details': 'خطأ في التحميل: {error}',
    'added_to_cart': 'تمت إضافة {name} إلى السلة',
    'page_not_found_title': 'الصفحة غير موجودة',
    'no_route_for': 'لا يوجد مسار لـ: {route}',
    'back_to_home': 'العودة إلى الرئيسية',
    'ad_mega_sale_title': '🎯 تخفيضات كبرى -50%',
    'ad_mega_sale_subtitle': 'على جميع الهواتف الذكية',
    'ad_free_delivery_title': '🚚 توصيل مجاني',
    'ad_free_delivery_subtitle': 'للطلبات فوق 100€',
    'ad_flash_deal_title': '⚡ صفقة سريعة',
    'ad_flash_deal_subtitle': 'عروض جديدة كل يوم',
    'ad_promo_code_title': '🎁 كود خصم: SAVE20',
    'ad_promo_code_subtitle': 'خصم فوري 20%',
    'notifications': 'الإشعارات',
    'appearance': 'المظهر',
    'privacy': 'الخصوصية',
    'danger_zone': 'منطقة الخطر',
    'push_notifications': 'إشعارات فورية',
    'receive_notifications': 'تلقي الإشعارات',
    'notification_preferences': 'تفضيلات الإشعارات',
    'choose_categories': 'اختيار الفئات',
    'sounds': 'الأصوات',
    'enable_sound_effects': 'تفعيل المؤثرات الصوتية',
    'vibrations': 'الاهتزازات',
    'haptic_feedback': 'الاستجابة اللمسية',
    'dark_mode': 'الوضع الداكن',
    'enable_dark_theme': 'تفعيل المظهر الداكن',
    'app_language': 'لغة التطبيق',
    'change_password': 'تغيير كلمة المرور',
    'change_password_subtitle': 'تحديث كلمة المرور الخاصة بك',
    'privacy_policy': 'سياسة الخصوصية',
    'privacy_policy_subtitle': 'كيف نحمي بياناتك',
    'terms_of_service': 'شروط الاستخدام',
    'terms_of_service_subtitle': 'قراءة شروط الاستخدام',
    'clear_cache': 'مسح ذاكرة التخزين المؤقت',
    'cache_cleared_success': 'تم مسح ذاكرة التخزين المؤقت بنجاح',
    'logout_confirm_message': 'هل تريد تسجيل الخروج حقًا؟',
    'enable_disable_all_notifications': 'تفعيل/تعطيل جميع الإشعارات',
    'notification_category_orders_subtitle': 'حالة الطلب، التوصيل، الإلغاء',
    'notification_category_promotions_subtitle': 'عروض، خصومات، جديد',
    'notification_category_messages_subtitle': 'رسائل جديدة من الدعم/الدردشة',
    'save': 'حفظ',
    'change_password_security_hint': 'لأمانك، أكّد كلمة المرور الحالية.',
    'current_password': 'كلمة المرور الحالية',
    'new_password': 'كلمة المرور الجديدة',
    'confirm_password': 'تأكيد كلمة المرور',
    'error_user_email_not_found': 'تعذّر المتابعة: البريد الإلكتروني للمستخدم غير موجود.',
    'password_min_length': 'يجب أن تحتوي كلمة المرور الجديدة على 6 أحرف على الأقل.',
    'passwords_do_not_match': 'كلمتا المرور غير متطابقتين.',
    'password_changed_success': 'تم تغيير كلمة المرور.',
    'error_with_details': 'خطأ: {error}',
    'share_unavailable_with_details': 'تعذّر المشاركة: {error}',
    'link_copied': 'تم نسخ الرابط',
    'copy_unavailable_with_details': 'تعذّر النسخ: {error}',
    'open_link_unavailable': 'تعذّر فتح الرابط',
    'image': 'صورة',
    'download': 'تنزيل',
    'share': 'مشاركة',
    'view_fullscreen': 'عرض بملء الشاشة',
    'copy_link': 'نسخ الرابط',
    'chat_error_sending_with_details': 'خطأ في الإرسال: {error}',
    'chat_error_sending_image_with_details': 'خطأ في إرسال الصورة: {error}',
    'image_upload_failed': 'فشل رفع الصورة',
    'support_client': 'دعم العملاء',
    'order_number': 'الطلب #{id}',
    'start_conversation': 'ابدأ المحادثة',
    'we_are_here_to_help': 'نحن هنا لمساعدتك',
    'type_your_message': 'اكتب رسالتك...',
    'conversation_info_title': 'معلومات المحادثة',
    'label_id': 'المعرّف',
    'label_status': 'الحالة',
    'label_priority': 'الأولوية',
    'label_order': 'الطلب',
    'label_created_at': 'تم الإنشاء في',
    'today': 'اليوم',
    'conversation_status_active': 'نشطة',
    'conversation_status_resolved': 'تم الحل',
    'conversation_status_archived': 'مؤرشفة',
    'conversation_status_pending': 'قيد الانتظار',
    'conversation_priority_urgent': 'عاجل',
    'conversation_priority_high': 'مرتفعة',
    'conversation_priority_normal': 'عادية',
    'conversation_priority_low': 'منخفضة',
    'privacy_policy_section1_title': '1. البيانات التي نجمعها',
    'privacy_policy_section1_body':
        'نجمع المعلومات اللازمة لإنشاء حسابك، ومعالجة طلباتك، وتحسين التجربة (مثل: البريد الإلكتروني، الاسم، رقم الهاتف، العناوين).',
    'privacy_policy_section2_title': '2. استخدام البيانات',
    'privacy_policy_section2_body':
        'تُستخدم البيانات من أجل: المصادقة، التوصيل، دعم العملاء، التحليلات، ومنع الاحتيال.',
    'privacy_policy_section2_body_location':
        'إذا استخدمت ميزة تحديد الموقع من أجل التوصيل، فقد نعالج موقعك فقط لتسهيل عملية التوصيل. لا يُطلب الموقع إلا بعد إجراء صريح (مثل زر "استخدم موقعي") عند إجراء طلب أو طلب خاص، ولا يتم جمعه في الخلفية.',
    'privacy_policy_section3_title': '3. الإشعارات',
    'privacy_policy_section3_body':
        'إذا فعّلت الإشعارات، قد يستخدم التطبيق معرّف إشعارات (Token) لإرسال رسائل لك (حالة الطلب، العروض).',
    'privacy_policy_section4_title': '4. مشاركة البيانات',
    'privacy_policy_section4_body':
        'نحن لا نبيع بياناتك. قد تعالج بعض الخدمات التقنية (مثل المصادقة وقاعدة البيانات) البيانات لتقديم الخدمة.',
    'privacy_policy_section5_title': '5. حقوقك',
    'privacy_policy_section5_body':
        'يمكنك طلب الوصول إلى بياناتك أو تصحيحها أو حذفها وفقًا للأنظمة المعمول بها.',
    'terms_of_service_section1_title': '1. الهدف',
    'terms_of_service_section1_body': 'تحدد هذه الشروط قواعد استخدام التطبيق والخدمات المرتبطة به.',
    'terms_of_service_section2_title': '2. حساب المستخدم',
    'terms_of_service_section2_body': 'أنت مسؤول عن الحفاظ على سرية بيانات الدخول وعن استخدام حسابك.',
    'terms_of_service_section3_title': '3. الطلبات والدفع',
    'terms_of_service_section3_body': 'تخضع الطلبات للتوفر. قد تتغير الأسعار والرسوم. وقد تتم معالجة الدفع بواسطة مزود خدمة.',
    'terms_of_service_section4_title': '4. التوصيل',
    'terms_of_service_section4_body': 'مواعيد التوصيل تقديرية. تأكد من إدخال عنوان صحيح.',
    'terms_of_service_section4_body_location':
        'إذا اخترت استخدام ميزة تحديد الموقع، فقد يُستخدم موقعك فقط لتسهيل عملية التوصيل. لا يُطلب الموقع إلا بعد إجراء صريح (مثل زر "استخدم موقعي") عند إجراء طلب أو طلب خاص، ولا يتم جمعه في الخلفية.',
    'terms_of_service_section5_title': '5. الدعم',
    'terms_of_service_section5_body': 'لأي استفسار، تواصل مع الدعم عبر القنوات المتاحة داخل التطبيق.',
  };

  String translate(String key) {
    switch (locale.languageCode) {
      case 'en':
        if (!_englishTranslations.containsKey(key)) {
          I18nAudit.instance.reportMissingKey(key: key, locale: locale);
        }
        return _englishTranslations[key] ?? key;
      case 'fr':
        if (!_frenchTranslations.containsKey(key)) {
          I18nAudit.instance.reportMissingKey(key: key, locale: locale);
        }
        return _frenchTranslations[key] ?? key;
      case 'ar':
        if (!_arabicTranslations.containsKey(key)) {
          I18nAudit.instance.reportMissingKey(key: key, locale: locale);
        }
        return _arabicTranslations[key] ?? key;
      default:
        if (!_englishTranslations.containsKey(key)) {
          I18nAudit.instance.reportMissingKey(key: key, locale: locale);
        }
        return _englishTranslations[key] ?? key;
    }
  }

  String translateParams(String key, Map<String, String> params) {
    var value = translate(key);
    for (final entry in params.entries) {
      value = value.replaceAll('{${entry.key}}', entry.value);
    }
    return value;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'fr', 'ar'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
